//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resources.rc
//
#define ID_INDICATOR_SEQPOS             52
#define ID_INDICATOR_PATTERN            53
#define ID_INDICATOR_LINE               54
#define ID_INDICATOR_TIME               55
#define ID_INDICATOR_EDIT               56
#define ID_INDICATOR_FOLLOW             57
#define ID_INDICATOR_NOTEOFF            58
#define ID_INDICATOR_TWEAKS             59
#define ID_INDICATOR_OCTAVE             60
#define IDC_SEQEDITBOX                  61
#define IDR_MAINFRAME                   101
#define IDD_SONGBAR                     102
#define IDD_WAVED_ZOOMBAR               103
#define IDD_MACHINEBAR                  108
#define IDD_SEQUENCER                   112
#define IDD_EXTENSIONBAR                113
#define IDD_SONGPROP                    118
#define IDD_NEWMACHINE                  120
#define IDB_MACHINETYPE                 121
#define IDD_CONFIG_KEY                  123
#define IDD_CONFIGURATION               125
#define IDD_CONFIG_DIRECTORIES          126
#define IDD_CONFIG_SKIN                 127
#define IDD_CONFIG_OUTPUT               128
#define IDD_CONFIG_WAVEOUT              129
#define IDD_CONFIG_DSOUND               131
#define IDD_CONFIG_MIDI_INPUT           134
#define IDD_INFO                        136
#define IDB_CPU                         137
#define IDD_MIDI_MONITOR                139
#define IDD_ABOUTBOX                    141
#define IDD_GREETS                      144
#define IDD_ABOUT_GREETS                144
#define IDR_WAVEFRAME                   146
#define IDD_WAVED_AMPLIFY               147
#define IDD_PATDLG                      154
#define IDD_WIREDIALOG                  155
#define IDD_NEWVAL                      156
#define IDD_MACPROP                     157
#define IDD_GEAR_SAMPLER                163
#define IDB_SAMPLER                     164
#define IDD_GEAR_MASTER                 172
#define IDD_GEAR_VSTPARAMS              174
#define IDR_FRAMEMACHINE                175
#define IDB_KNOB                        177
#define IDR_POPUPMENU                   180
#define IDD_PRESETS                     181
#define IDD_SWINGFILL                   187
#define IDD_CONFIG_ASIO                 188
#define IDB_PATTERN_HEADER_SKIN         194
#define IDB_MACHINE_SKIN                195
#define IDB_ASIO                        198
#define IDD_GEARRACK                    201
#define IDD_NEW_VOLUME                  202
#define IDD_SAVEWAVDLG                  203
#define IDD_PROGRESS_DIALOG             204
#define IDD_GEAR_SAMPULSEUI             214
#define IDD_GEAR_SAMPULSE_GEN           215
#define IDD_INST_SAMPULSE_INSTRUMENT    217
#define IDD_GEAR_SAMPULSE_MIXER         222
#define IDB_SAMPULSE                    226
#define IDR_MENU_ENV_EDIT               230
#define IDB_KEYS_NORMAL                 231
#define IDB_KEYS_SHARP                  232
#define IDB_KEYS_BACK                   234
#define IDD_INTERPOLATE_CURVE           240
#define IDD_WAVED_MIX                   255
#define IDD_WAVED_INSERTSILENCE         257
#define IDD_WAVED_CROSSFADE             258
#define IDR_WAVEDFRAME                  258
#define IDR_WAVED_POPUP                 260
#define IDD_SPECIALKEYS                 264
#define IDD_GEAR_WAVEIN                 271
#define IDD_TRANSFORMPATTERN            277
#define IDD_CONFIG_MIDI_REMAP           278
#define IDD_CONFIG_WASAPI               280
#define IDR_SEQUENCE_MENU               284
#define IDI_LESSLESS                    286
#define IDI_LESS                        289
#define IDI_MORE                        290
#define IDI_MOREMORE                    291
#define IDI_PLUS                        292
#define IDI_MINUS                       293
#define IDI_LOWER                       294
#define IDI_GREATER                     296
#define IDR_POPUP_MACHINE               297
#define IDD_WIRE_CHANMAP                314
#define IDD_INST_SAMPULSE_INSTAMP       316
#define IDD_INST_SAMPULSE_INSTPAN       317
#define IDD_INST_SAMPULSE_INSTFIL       318
#define IDD_INST_SAMPULSE_ENVDLG        320
#define IDD_INST_SAMPLER_INST           321
#define IDD_PLOTTER                     322
#define IDR_INSTRUMENTEDIT              324
#define IDD_INST_NOTEMAP_INDIV          326
#define IDI_ICON2014                    328
#define IDI_ICON2000                    329
#define IDB_SPLASH2014                  331
#define IDB_MASTER_SKIN                 332
#define IDB_MIXER_SKIN                  333
#define IDB_MAINTOOLBAR24               342
#define IDB_MAINTOOLBAR24MASK           343
#define IDD_INST_NOTEMAP                344
#define IDC_DRIVER                      1000
#define IDC_CONFIG                      1001
#define IDC_MIDI_DRIVER                 1002
#define IDC_SYNC_DRIVER                 1003
#define IDC_MIDI_HEADROOM               1004
#define IDC_MIDI_HEADROOM_SPIN          1005
#define IDC_CONFIG_DEVICE               1007
#define IDC_CONFIG_SAMPLERATE           1008
#define IDC_CONFIG_BUFNUM               1009
#define IDC_CONFIG_BUFNUM_SPIN          1010
#define IDC_CONFIG_BUFSIZE              1011
#define IDC_CONFIG_BUFSIZE_SPIN         1012
#define IDC_CONFIG_LATENCY              1014
#define IDC_DSOUND_DEVICE               1015
#define IDC_DSOUND_BUFNUM_EDIT          1016
#define IDC_DSOUND_BUFSIZE_SPIN         1017
#define IDC_DSOUND_BUFSIZE_EDIT         1018
#define IDC_DSOUND_BUFNUM_SPIN          1019
#define IDC_DSOUND_LATENCY              1020
#define IDC_DSOUND_SAMPLERATE_COMBO     1021
#define IDC_WASAPI_BITS                 1022
#define IDC_BROWSESONG                  1024
#define IDC_DSOUND_BITDEPTH             1024
#define IDC_SONGEDIT                    1025
#define IDC_BROWSEINST                  1026
#define IDC_INSTEDIT                    1027
#define IDC_BROWSEVST32                 1028
#define IDC_VSTEDIT32                   1029
#define IDC_BROWSEPLUGIN                1030
#define IDC_PLUGINEDIT                  1031
#define IDC_FT2_HOME_END                1032
#define IDC_SKINEDIT                    1032
#define IDC_FT2DEL                      1033
#define IDC_BROWSESKIN                  1033
#define IDC_SHIFTARROWS                 1034
#define IDC_WAVERECEDIT                 1034
#define IDC_PLAY_R_CTRL                 1035
#define IDC_BROWSEWAVEREC               1035
#define IDC_KEY0                        1036
#define IDC_CMDLIST                     1037
#define IDC_BROWSE_USERPRESET           1037
#define IDC_ROWC                        1038
#define IDC_WINDOWSBLOCKS               1038
#define IDC_VSTEDIT64                   1038
#define IDC_BEATC                       1039
#define IDC_BROWSEVST64                 1039
#define IDC_4BEAT                       1040
#define IDC_BROWSE_LUASCRIPTS           1040
#define IDC_PATTERN_FONTFACE            1041
#define IDC_BROWSE_LUASCRIPTS2          1041
#define IDC_BROWSE_LADSPA               1041
#define IDC_FONTC                       1043
#define IDC_PATTERN_HEADER_SKIN         1044
#define IDC_VUBAR_COLOUR                1045
#define IDC_VUBACK_COLOUR               1046
#define IDC_VUCLIP_COLOUR               1047
#define IDC_ABOUTBMP                    1048
#define IDC_MACHINE_SKIN                1048
#define IDC_HEADER                      1049
#define IDC_MACHINE_FONTFACE            1049
#define IDC_MACHINE_FONTFACE2           1050
#define IDC_STEINBERGCOPY               1051
#define IDC_EDIT5                       1052
#define IDC_SHOWATSTARTUP               1053
#define IDC_ASIO                        1054
#define IDC_ADSRBASE                    1055
#define IDC_ADSRMOD                     1056
#define IDC_ADSRATT                     1057
#define IDC_ADSRDEC                     1058
#define IDC_ADSRSUS                     1059
#define IDC_AMPFRAME                    1060
#define IDC_ADSRREL                     1060
#define IDC_SLIDER1                     1061
#define IDC_VOLCUTOFFPAN                1061
#define IDC_SLIDER2                     1062
#define IDC_FADEOUTRES                  1062
#define IDC_SLIDER3                     1063
#define IDC_NOTEMOD                     1063
#define IDC_SWING1                      1064
#define IDC_A_A_LABEL                   1065
#define IDC_SWING2                      1065
#define IDC_A_D_LABEL                   1066
#define IDC_A_S_LABEL                   1068
#define IDC_A_R_LABEL                   1070
#define IDC_FILFRAME                    1071
#define IDC_F_A_LABEL                   1072
#define IDC_F_D_LABEL                   1073
#define IDC_F_S_LABEL                   1077
#define IDC_F_R_LABEL                   1079
#define IDC_CUTOFF_LBL                  1082
#define IDC_F_AMOUNTLABEL               1083
#define IDC_STATUSPARAM                 1084
#define IDC_AUTODEC                     1085
#define IDC_LABELQ                      1085
#define IDC_STATIC1                     1086
#define IDC_STATIC2                     1087
#define IDC_STATIC3                     1088
#define IDC_LNOTEMODNOTE                1089
#define IDC_MACHINELIST                 1090
#define IDC_STATIC18                    1090
#define IDC_BUTTON1                     1091
#define IDC_BUTTON2                     1092
#define IDC_ZOOMIN                      1092
#define IDC_BUTTON3                     1093
#define IDC_BUTTON4                     1094
#define IDC_INS_DECOCTAVE               1094
#define IDC_BPM_DECONE                  1095
#define IDC_OPENWAVEEDITOR              1099
#define IDC_BPM_ADDONE                  1099
#define IDC_KILL_INSTRUMENT             1105
#define IDC_EDIT1                       1109
#define IDC_EDIT2                       1110
#define IDC_EDIT_AUTHOR                 1111
#define IDC_EDIT_COMMENTS               1112
#define IDC_CHECK1                      1113
#define IDC_REPLACEINS                  1113
#define IDC_BROWSER                     1114
#define IDC_ENV_SUSEND                  1114
#define IDC_SPKEYS_SHIFT                1114
#define IDC_REPLACENOTE                 1114
#define IDC_NAMELABEL                   1115
#define IDC_ENV_LOOPSTART               1115
#define IDC_REPLACECMD                  1116
#define IDC_VERSIONLABEL                1117
#define IDC_DLLNAMELABEL                1118
#define IDC_SHOWDLLNAME                 1119
#define IDC_SHOWEFFNAME                 1120
#define IDC_BYTYPE                      1121
#define IDC_BYCLASS                     1122
#define IDC_SPIN1                       1123
#define IDC_APIVERSIONLABEL             1123
#define IDC_GREETSLIST                  1124
#define IDC_TEXT                        1125
#define IDC_LOOPSTART                   1128
#define IDC_LOOPEND                     1129
#define IDC_LOOPTYPE                    1130
#define IDC_LOOPOFF                     1131
#define IDC_LOOPFORWARD                 1132
#define IDC_WAVELENGTH                  1134
#define IDC_VOLABEL                     1135
#define IDC_COMBO1                      1137
#define IDC_PANLABEL                    1138
#define IDC_PAGEUPSTEPS                 1138
#define IDC_REPLNOTECOMB                1138
#define IDC_NNA_COMBO                   1139
#define IDC_RPAN                        1140
#define IDC_RCUT                        1141
#define IDC_RRES                        1142
#define IDC_CHECK4                      1144
#define IDC_LOOPEDIT                    1145
#define IDC_LOCKINSTNUMBER              1146
#define IDC_TRACKLABEL2                 1152
#define IDC_TRACKSLIDER2                1153
#define IDC_CPUIDLE_LABEL               1162
#define IDC_CPUL                        1163
#define IDC_MCPULABEL                   1164
#define IDC_MCPULABEL2                  1165
#define IDC_MEM_RESO                    1166
#define IDC_MEM_RESO2                   1167
#define IDC_MEM_RESO3                   1168
#define IDC_MEM_RESO4                   1169
#define IDC_LVUM                        1184
#define IDC_FRAMECLIP                   1186
#define IDC_CLIPBUT                     1187
#define IDC_TPBLABEL                    1188
#define IDC_BPMLABEL                    1189
#define IDC_DEC_TPB                     1190
#define IDC_INC_TPB                     1191
#define IDC_COMBOSTEP                   1193
#define IDC_TRACKCOMBO                  1194
#define IDC_AUXSELECT                   1195
#define IDC_BAR_COMBOGEN                1196
#define IDC_BAR_COMBOINS                1197
#define IDC_B_DECGEN                    1198
#define IDC_B_INCGEN                    1199
#define IDC_B_DECWAV                    1200
#define IDC_B_INCWAV                    1201
#define IDC_LOADWAVE                    1202
#define IDC_EDITWAVE                    1203
#define IDC_WAVEBUT                     1204
#define IDC_SAVEWAVE                    1205
#define IDC_FOLLOW                      1206
#define IDC_SEQLIST                     1207
#define IDC_INCSHORT                    1208
#define IDC_DECSHORT                    1209
#define IDC_SEQNEW                      1212
#define IDC_SEQINS                      1213
#define IDC_SEQDUPLICATE                1226
#define IDC_LENGTH                      1227
#define IDC_WRAP                        1228
#define IDC_MULTICHANNEL_AUDITION       1229
#define IDC_RECORD_NOTEOFF              1230
#define IDC_CENTERCURSOR                1231
#define IDC_CURSORDOWN                  1232
#define IDC_SHOWA440                    1232
#define IDC_MUTE                        1233
#define IDC_SHOW_INFO_ON_LOAD           1233
#define IDC_BYPASS                      1234
#define IDC_FILE_SAVE_REMINDERS         1234
#define IDC_SOLO                        1235
#define IDC_SAVE                        1237
#define IDC_DELETE                      1238
#define IDC_IMPORT                      1239
#define IDC_ADDEFFECTHERE               1239
#define IDC_PREVIEW                     1240
#define IDC_EXPORT                      1241
#define IDC_PRESETSLIST                 1242
#define IDC_BUFFER_USED                 1243
#define IDC_BUFFER_CAPACITY             1244
#define IDF_PSYCLE_MIDI_ACTIVE          1245
#define IDF_RECEIVING_MIDI_DATA         1246
#define IDC_EVENTS_LOST                 1247
#define IDC_CLEAR_EVENTS_LOST           1248
#define IDC_SYNC_OFFSET                 1249
#define IDC_SYNC_ADJUST                 1250
#define IDC_SYNC_LATENCY                1251
#define IDF_SYNCRONISING                1252
#define IDF_RESYNC_TRIGGERED            1253
#define IDF_MIDI_SYNC_START             1254
#define IDF_MIDI_SYNC_CLOCK             1255
#define IDF_MIDI_SYNC_STOP              1256
#define IDF_EMULATED_SYNC_START         1257
#define IDF_EMULATED_SYNC_CLOCK         1258
#define IDD_INST_SAMPLEBANK             1258
#define IDF_EMULATED_SYNC_STOP          1259
#define IDD_INSTRUMENTUI                1259
#define IDF_SYNC_TICK                   1260
#define IDD_INST_SAMPULSE_INSTPIT_NEW   1260
#define IDC_MIDI_VERSION                1261
#define IDC_CHANNEL_MAP                 1262
#define IDC_CH1                         1263
#define IDC_CH2                         1264
#define IDC_CH3                         1265
#define IDC_CH4                         1266
#define IDC_CH5                         1267
#define IDC_CH6                         1268
#define IDC_CH7                         1269
#define IDC_CH8                         1270
#define IDC_CH9                         1271
#define IDC_CH10                        1272
#define IDC_CH11                        1273
#define IDC_CH12                        1274
#define IDC_CH13                        1275
#define IDC_CH14                        1276
#define IDC_CH15                        1277
#define IDC_CH16                        1278
#define IDC_MIDI_RECORD_PIT             1279
#define IDC_MIDI_RECORD_VEL             1280
#define IDC_MIDI_RECORD_0               1281
#define IDC_MIDI_RECORD_1               1282
#define IDC_MIDI_RECORD_2               1283
#define IDC_MIDI_RECORD_3               1284
#define IDC_MIDI_RECORD_4               1285
#define IDC_MIDI_RECORD_5               1286
#define IDC_MIDI_RECORD_6               1287
#define IDC_MIDI_RECORD_7               1288
#define IDC_MIDI_RECORD_8               1289
#define IDC_MIDI_RECORD_9               1290
#define IDC_MIDI_RECORD_10              1291
#define IDC_MIDI_RECORD_11              1292
#define IDC_MIDI_RECORD_12              1293
#define IDC_MIDI_RECORD_13              1294
#define IDC_MIDI_RECORD_14              1295
#define IDC_MIDI_RECORD_15              1296
#define IDC_MIDI_MESSAGE_0              1297
#define IDC_MIDI_MESSAGE_1              1298
#define IDC_MIDI_MESSAGE_2              1299
#define IDC_MIDI_MESSAGE_3              1300
#define IDC_MIDI_MESSAGE_4              1301
#define IDC_MIDI_MESSAGE_5              1302
#define IDC_MIDI_MESSAGE_6              1303
#define IDC_MIDI_MESSAGE_7              1304
#define IDC_MIDI_MESSAGE_8              1305
#define IDC_MIDI_MESSAGE_9              1306
#define IDC_MIDI_MESSAGE_10             1307
#define IDC_MIDI_MESSAGE_11             1308
#define IDC_MIDI_MESSAGE_12             1309
#define IDC_MIDI_MESSAGE_13             1310
#define IDC_MIDI_MESSAGE_14             1311
#define IDC_MIDI_MESSAGE_15             1312
#define IDC_MIDI_TYPE_PIT               1313
#define IDC_MIDI_TYPE_VEL               1314
#define IDC_MIDI_TYPE_0                 1315
#define IDC_MIDI_TYPE_1                 1316
#define IDC_MIDI_TYPE_2                 1317
#define IDC_MIDI_TYPE_3                 1318
#define IDC_MIDI_TYPE_4                 1319
#define IDC_MIDI_TYPE_5                 1320
#define IDC_MIDI_TYPE_6                 1321
#define IDC_MIDI_TYPE_7                 1322
#define IDC_MIDI_TYPE_8                 1323
#define IDC_MIDI_TYPE_9                 1324
#define IDC_MIDI_TYPE_10                1325
#define IDC_MIDI_TYPE_11                1326
#define IDC_MIDI_TYPE_12                1327
#define IDC_MIDI_TYPE_13                1328
#define IDC_MIDI_TYPE_14                1329
#define IDC_MIDI_TYPE_15                1330
#define IDC_MIDI_COMMAND_VEL            1331
#define IDC_MIDI_COMMAND_PIT            1332
#define IDC_MIDI_COMMAND_0              1333
#define IDC_MIDI_COMMAND_1              1334
#define IDC_MIDI_COMMAND_2              1335
#define IDC_MIDI_COMMAND_3              1336
#define IDC_MIDI_COMMAND_4              1337
#define IDC_MIDI_COMMAND_5              1338
#define IDC_MIDI_COMMAND_6              1339
#define IDC_MIDI_COMMAND_7              1340
#define IDC_MIDI_COMMAND_8              1341
#define IDC_MIDI_COMMAND_9              1342
#define IDC_MIDI_COMMAND_10             1343
#define IDC_MIDI_COMMAND_11             1344
#define IDC_MIDI_COMMAND_12             1345
#define IDC_MIDI_COMMAND_13             1346
#define IDC_MIDI_COMMAND_14             1347
#define IDC_MIDI_COMMAND_15             1348
#define IDC_MIDI_FROM_PIT               1349
#define IDC_MIDI_FROM_VEL               1350
#define IDC_MIDI_FROM_0                 1351
#define IDC_MIDI_FROM_1                 1352
#define IDC_MIDI_FROM_2                 1353
#define IDC_MIDI_FROM_3                 1354
#define IDC_MIDI_FROM_4                 1355
#define IDC_MIDI_FROM_5                 1356
#define IDC_MIDI_FROM_6                 1357
#define IDC_MIDI_FROM_7                 1358
#define IDC_MIDI_FROM_8                 1359
#define IDC_MIDI_FROM_9                 1360
#define IDC_MIDI_FROM_10                1361
#define IDC_MIDI_FROM_11                1362
#define IDC_MIDI_FROM_12                1363
#define IDC_MIDI_FROM_13                1364
#define IDC_MIDI_FROM_14                1365
#define IDC_MIDI_FROM_15                1366
#define IDC_MIDI_TO_PIT                 1367
#define IDC_MIDI_TO_VEL                 1368
#define IDC_MIDI_TO_0                   1369
#define IDC_MIDI_TO_1                   1370
#define IDC_MIDI_TO_2                   1371
#define IDC_MIDI_TO_3                   1372
#define IDC_MIDI_TO_4                   1373
#define IDC_MIDI_TO_5                   1374
#define IDC_MIDI_TO_7                   1375
#define IDC_MIDI_TO_6                   1376
#define IDC_MIDI_TO_8                   1377
#define IDC_MIDI_TO_9                   1378
#define IDC_MIDI_TO_10                  1379
#define IDC_MIDI_TO_11                  1380
#define IDC_MIDI_TO_12                  1381
#define IDC_MIDI_TO_13                  1382
#define IDC_MIDI_TO_14                  1383
#define IDC_MIDI_TO_15                  1384
#define IDC_MIDI_GEN_SELECT             1385
#define IDC_MIDI_INSTR_SELECT           1386
#define IDC_PBG_CAN                     1401
#define IDC_MIDI_RAW                    1401
#define IDC_ROW_CAN                     1402
#define IDC_BEAT_CAN                    1403
#define IDC_FONT_CAN                    1404
#define IDC_4BEAT_CAN                   1405
#define IDC_VU1_CAN                     1406
#define IDC_VU2_CAN                     1407
#define IDC_VU3_CAN                     1408
#define IDC_MBG_CAN                     1409
#define IDC_REFRESH                     1410
#define IDC_MWIRE_COL                   1410
#define IDC_RECORD_TWEAKS               1411
#define IDC_MPOLY_COL                   1411
#define IDC_CENTER_TEMPO                1412
#define IDC_PBG_SEPARATOR               1412
#define IDC_VARIANCE                    1413
#define IDC_PBG_SEPARATOR2              1413
#define IDC_WIDTH                       1414
#define IDC_ROW_CAN2                    1414
#define IDC_PHASE                       1415
#define IDC_BEAT_CAN2                   1415
#define IDC_OFFSET                      1416
#define IDC_4BEAT_CAN2                  1416
#define IDC_BG_COLOUR                   1417
#define IDC_WIRE_COLOUR                 1418
#define IDC_POLY_COLOUR                 1419
#define IDC_MACHINEFONTTOP_CAN          1420
#define IDC_PLAYBAR_CAN                 1421
#define IDC_PLAYBAR_CAN2                1422
#define IDC_WIRE_WIDTH                  1423
#define IDC_FONTPLAY_CAN                1424
#define IDC_MASTERPEAK                  1425
#define IDC_FONTSEL_CAN                 1425
#define IDC_PATSEPARATORC               1426
#define IDC_PATTERNBACKC                1427
#define IDC_FONTCURSOR_CAN              1428
#define IDC_COMBOOCTAVE                 1428
#define IDC_PATSEPARATORC2              1429
#define IDC_GEAR_RACK                   1429
#define IDC_SELECTION_CAN               1430
#define IDC_CURSOR_CAN                  1431
#define IDC_SELECTION_CAN2              1432
#define IDC_CURSOR_CAN2                 1433
#define IDC_PATTERNBACKC2               1434
#define IDC_PBG_CAN2                    1435
#define IDC_FONT_CAN2                   1436
#define IDC_FONTPLAY_CAN2               1437
#define IDC_FONTSEL_CAN2                1438
#define IDC_FONTCURSOR_CAN2             1439
#define IDC_LINE_NUMBERS                1440
#define IDC_ROWC2                       1441
#define IDC_BEATC2                      1442
#define IDC_4BEAT2                      1443
#define IDC_PLAYBARC                    1444
#define IDC_PLAYBARC2                   1445
#define IDC_FONTPLAYC                   1446
#define IDC_SELECTIONC                  1447
#define IDC_CURSORC                     1448
#define IDC_SELECTIONC2                 1449
#define IDC_CURSORC2                    1450
#define IDC_FONTSELC                    1451
#define IDC_FONTCURSORC                 1452
#define IDC_FONTC2                      1453
#define IDC_FONTPLAYC2                  1454
#define IDC_FONTSELC2                   1455
#define IDC_FONTCURSORC2                1456
#define IDC_LINE_NUMBERS_HEX            1457
#define IDC_EXPORTREG                   1458
#define IDC_IMPORTREG                   1459
#define IDC_SLIDERMASTER                1460
#define IDC_PATTERN_FONT_Y              1460
#define IDC_DEFAULTS                    1460
#define IDC_SLIDERM1                    1461
#define IDC_PATTERN_FONT_X              1461
#define IDC_NONE                        1461
#define IDC_SLIDERM2                    1462
#define IDC_PATTERN_FONT_POINT          1462
#define IDC_SPECIALKEYS                 1462
#define IDC_SLIDERM3                    1463
#define IDC_MACHINE_FONT_POINT          1463
#define IDC_SLIDERM4                    1464
#define IDC_MV_FONT_COLOUR              1464
#define IDC_SLIDERM5                    1465
#define IDC_MBG_MV_FONT                 1465
#define IDC_SLIDERM6                    1466
#define IDC_WIREAA                      1466
#define IDC_SLIDERM7                    1467
#define IDC_MACHINE_FONT_POINT2         1467
#define IDC_SLIDERM8                    1468
#define IDC_MV_FONT_COLOUR2             1468
#define IDC_SLIDERM9                    1469
#define IDC_MBG_MV_FONT2                1469
#define IDC_SLIDERM10                   1470
#define IDC_LINE_NUMBERS_CURSOR         1470
#define IDC_SLIDERM11                   1471
#define IDC_DRAW_EMPTY_DATA             1471
#define IDC_SLIDERM12                   1472
#define IDC_DRAW_MAC_INDEX              1472
#define IDC_SEQCUT                      1473
#define IDC_TRIANGLESIZE                1473
#define IDC_SEQCOPY                     1474
#define IDC_MACHINETOP_CAN              1474
#define IDC_SEQPASTE                    1475
#define IDC_MACHINE_BITMAP              1475
#define IDC_SEQDELETE                   1476
#define IDC_MACHINEBOTTOM_CAN           1476
#define IDC_MACHINEFONTBOTTOM_CAN       1477
#define IDC_MACHINETITLE_CAN            1478
#define IDC_MACHINEFONTTITLE_CAN        1479
#define IDC_MACHINEFONTTOP_CAN2         1480
#define IDC_MACHINETOP_CAN2             1481
#define IDC_MODE                        1481
#define IDC_SLIDER                      1482
#define IDC_MACHINEBOTTOM_CAN2          1482
#define IDC_MACHINEFONTBOTTOM_CAN2      1483
#define IDC_BUT_CHANNEL                 1483
#define IDC_VOLSLIDER                   1484
#define IDC_DEFAULTSKIN                 1484
#define IDC_ASIO_SAMPLERATE_COMBO       1486
#define IDC_ASIO_BUFFERSIZE_COMBO       1488
#define IDC_ASIO_LATENCY                1492
#define IDC_GEARLIST                    1493
#define IDC_ASIO_DRIVER                 1493
#define IDC_CREATE                      1494
#define IDC_VOLUME_DB                   1495
#define IDC_PROPERTIES                  1495
#define IDC_VOLUME_PER                  1496
#define IDC_EDIT_DB                     1496
#define IDC_PARAMETERS                  1496
#define IDC_EDIT_PER                    1497
#define IDC_EDIT_DEFLINES               1498
#define IDC_SPIN_DEFLINES               1499
#define IDC_TEXT_DEFLINES               1500
#define IDC_FILEBROWSE                  1501
#define IDC_FILENAME                    1502
#define IDC_PROGRESS                    1503
#define IDC_RANGESTART                  1506
#define IDC_RANGEEND                    1507
#define IDC_PATNUMBER                   1509
#define IDC_SAVEWIRESSEPARATED          1510
#define IDC_RECSONG                     1511
#define IDC_RECPATTERN                  1512
#define IDC_RECRANGE                    1513
#define IDC_AUTOSAVE_CURRENT_SONG       1514
#define IDC_SAVETRACKSSEPARATED         1514
#define IDC_AUTOSAVE_MINS               1515
#define IDC_SAVEGENERATORSEPARATED      1515
#define IDC_AUTOSAVE_MINS_SPIN          1516
#define IDC_RECBLOCK                    1516
#define IDC_CLONEMACHINE                1517
#define IDC_LINEEND                     1519
#define IDC_EXCHANGE                    1520
#define IDC_PATNUMBER2                  1520
#define IDC_TWEAK_SMOOTH                1521
#define IDC_RADIO_GEN                   1522
#define IDC_RECORD_UNARMED              1522
#define IDC_RADIO_EFX                   1523
#define IDC_NOTESTOEFFECTS              1523
#define IDC_RADIO_INS                   1524
#define IDC_PROGRESS1                   1524
#define IDC_CLONE                       1525
#define IDC_RADIO_INS2                  1525
#define IDC_RADIO_WAVES                 1525
#define IDC_CHECK_ALLOW                 1526
#define IDC_COMBO_RATE                  1528
#define IDC_CONTROL_PANEL               1529
#define IDC_COMBO_BITS                  1530
#define IDC_COMBO_CHANNELS              1531
#define IDC_CHECK_VUS                   1531
#define IDC_INS_DECNOTE                 1532
#define IDC_INS_INCNOTE                 1533
#define IDC_INS_INCOCTAVE               1534
#define IDC_NOTETUNE                    1535
#define IDC_MASTERSLIDER                1536
#define IDC_XMINTERPOL                  1545
#define IDC_XMPOLY                      1546
#define IDC_XMPANNINGMODE               1547
#define IDC_XMPOLYLABEL                 1549
#define IDC_NAVIGATION_IGNORES_STEP     1550
#define IDC_COMBO_NOISESHAPING          1551
#define IDC_MULTIPLEINSTANCES           1551
#define IDC_COMBOTWK                    1551
#define IDC_PATNAMES_COMBO              1551
#define IDC_INS_NNACOMBO                1552
#define IDC_FILTERTYPE                  1553
#define IDC_LEFT_VU                     1554
#define IDC_INS_DCTCOMBO                1555
#define IDC_SL_VOL_MASTER               1556
#define IDC_INS_DCACOMBO                1556
#define IDC_SL_VOL1                     1558
#define IDC_SL_VOL2                     1559
#define IDC_SL_VOL3                     1560
#define IDC_SL_VOL4                     1561
#define IDC_SL_VOL5                     1562
#define IDC_SL_VOL6                     1563
#define IDC_SL_VOL7                     1564
#define IDC_SL_VOL8                     1565
#define IDC_CH_SURR1                    1566
#define IDC_CH_SURR2                    1567
#define IDC_CH_SURR3                    1568
#define IDC_CH_SURR4                    1569
#define IDC_CH_SURR5                    1570
#define IDC_CH_SURR6                    1571
#define IDC_CH_SURR7                    1572
#define IDC_CH_SURR8                    1573
#define IDC_SL_CHANNELS                 1574
#define IDC_SL_PAN1                     1575
#define IDC_SL_PAN2                     1576
#define IDC_SL_PAN3                     1577
#define IDC_SL_PAN4                     1578
#define IDC_SL_PAN5                     1579
#define IDC_SL_PAN6                     1580
#define IDC_SL_PAN7                     1581
#define IDC_SL_PAN8                     1582
#define IDC_SL_RES1                     1583
#define IDC_SL_RES2                     1584
#define IDC_SL_RES3                     1585
#define IDC_SL_RES4                     1586
#define IDC_SL_RES5                     1587
#define IDC_SL_RES6                     1588
#define IDC_SL_RES7                     1589
#define IDC_SL_RES8                     1590
#define IDC_SL_CUTOFF1                  1591
#define IDC_SL_CUTOFF2                  1592
#define IDC_SL_CUTOFF3                  1593
#define IDC_SL_CUTOFF4                  1594
#define IDC_SL_CUTOFF5                  1595
#define IDC_SL_CUTOFF6                  1596
#define IDC_SL_CUTOFF7                  1597
#define IDC_SL_CUTOFF8                  1598
#define IDC_NAME1                       1599
#define IDC_NAME2                       1600
#define IDC_NAME3                       1601
#define IDC_NAME4                       1602
#define IDC_NAME5                       1603
#define IDC_NAME6                       1604
#define IDC_NAME7                       1605
#define IDC_NAME8                       1606
#define IDC_CH_MUTE8                    1607
#define IDC_CH_MUTE7                    1608
#define IDC_CH_MUTE6                    1609
#define IDC_CH_MUTE5                    1610
#define IDC_CH_MUTE2                    1611
#define IDC_CH_MUTE1                    1612
#define IDC_CH_MUTE3                    1613
#define IDC_CH_MUTE4                    1614
#define IDC_R_SHOWCHAN                  1615
#define IDC_R_SHOWVOICE                 1616
#define IDC_VOICESPLAYING               1617
#define IDC_VERSION_INFO_MULTI_LINE     1619
#define IDC_SUSTAINLOOP                 1620
#define IDC_LOOP                        1621
#define IDC_SPINSAMPLERATE              1625
#define IDC_SAMPLELIST                  1626
#define IDC_LOAD                        1627
#define IDC_DUPE                        1628
#define IDC_WAVENAME                    1629
#define IDC_SAMPLERATE                  1630
#define IDC_WAVESTEREO                  1631
#define IDC_DEFVOLUME                   1632
#define IDC_GLOBVOLUME                  1633
#define IDC_PAN                         1634
#define IDC_SAMPLENOTE                  1635
#define IDC_FINETUNE                    1636
#define IDC_VIBRATOATTACK               1637
#define IDC_VIBRATOSPEED                1638
#define IDC_VIBRATODEPTH                1639
#define IDC_PANENABLED                  1640
#define IDC_VIBRATOTYPE                 1641
#define IDC_SUSTAINSTART                1642
#define IDC_SUSTAINEND                  1643
#define IDC_FILTERED                    1643
#define IDC_COMMANDINFO                 1644
#define IDC_INS_NOTEMAP                 1645
#define IDC_INS_ENVELOPE                1646
#define IDC_LDEFVOL                     1653
#define IDC_LGLOBVOL                    1654
#define IDC_LPAN                        1655
#define IDC_LVIBRATOATTACK              1656
#define IDC_LVIBRATOSPEED               1657
#define IDC_LVIBRATODEPTH               1658
#define IDC_MACHINEGUI_BITMAP           1659
#define IDC_LSAMPLENOTE                 1659
#define IDC_MACHINEGUI_TOPFONTC         1660
#define IDC_LFINETUNE                   1660
#define IDC_MACHINEGUI_TOPC             1661
#define IDC_MACHINEGUI_BOTTOMC          1662
#define IDC_MACHINEGUI_BOTTOMFONTC      1663
#define IDC_MACHINEGUI_TITLEC           1664
#define IDC_MACHINEGUI_TITLEFONTC       1665
#define IDC_ENVADSR                     1665
#define IDC_MACHINEGUI_TOPFONTC2        1666
#define IDC_ENVFREEFORM                 1666
#define IDC_MACHINEGUI_TOPC2            1667
#define IDC_ENVMILLIS                   1667
#define IDC_MACHINEGUI_BOTTOMC2         1668
#define IDC_CUTOFFPAN                   1668
#define IDC_ENVTICKS                    1668
#define IDC_MACHINEGUI_BOTTOMFONTC2     1669
#define IDC_MOVECURSORPASTE             1670
#define IDC_LVOLCUTOFFPAN               1673
#define IDC_LFADEOUTRES                 1674
#define IDC_LNOTEMOD                    1675
#define IDC_LSWING                      1676
#define IDC_INSTRUMENTLIST              1677
#define IDC_LOADINS                     1678
#define IDC_SAVEINS                     1679
#define IDC_DUPEINS                     1680
#define IDC_DELETEINS                   1681
#define IDC_LSWING2                     1682
#define IDC_ENVCHECK                    1685
#define IDC_STATIC5                     1689
#define IDC_STATIC6                     1690
#define IDC_STATIC7                     1691
#define IDC_STATIC8                     1696
#define IDC_STATIC9                     1697
#define IDC_STATIC10                    1698
#define IDC_STATIC11                    1699
#define IDC_STATIC12                    1700
#define IDC_STATIC13                    1701
#define IDC_STATIC14                    1702
#define IDC_STATIC15                    1703
#define IDC_STATIC16                    1704
#define IDC_STATIC17                    1705
#define IDC_INS_NAME                    1706
#define IDC_LADSRBASE                   1709
#define IDC_LADSRMOD                    1710
#define IDC_LADSRATT                    1711
#define IDC_LADSRDEC                    1712
#define IDC_LADSRSUS                    1713
#define IDC_LADSRREL                    1714
#define IDC_WAVESCOPE                   1716
#define IDC_SLNOTEMODNOTE               1718
#define IDC_ENV_SUSBEGIN                1720
#define IDC_ENV_LOOPEND                 1721
#define IDC_INS_NOTESCROLL              1724
#define IDC_VAL                         1731
#define IDC_CURVE_TYPE                  1732
#define IDC_POS                         1733
#define IDC_INTER_MAX                   1734
#define IDC_INTER_MIN                   1735
#define IDC_HSCROLL                     1741
#define IDC_ZOOMSLIDE                   1742
#define IDC_ZOOMOUT                     1743
#define IDC_DESTGROUP                   1744
#define IDC_SRCGROUP                    1745
#define IDC_SRCVOL                      1746
#define IDC_DESTVOL                     1747
#define IDC_FADEINTIME                  1748
#define IDC_FADEOUTTIME                 1749
#define IDC_FADEINCHECK                 1750
#define IDC_FADEOUTCHECK                1751
#define IDC_DESTVOL_TEXT                1753
#define IDC_SRCVOL_TEXT                 1754
#define IDC_RADIO_ATSTART               1755
#define IDC_RADIO_ATEND                 1756
#define IDC_DESTENDVOL_TEXT             1756
#define IDC_RADIO_ATCURSOR              1757
#define IDC_SRCSTARTVOL                 1758
#define IDC_SRCENDVOL                   1759
#define IDC_DESTSTARTVOL                1760
#define IDC_DESTENDVOL                  1761
#define IDC_SRCENDVOL_TEXT              1762
#define IDC_SRCSTARTVOL_TEXT            1763
#define IDC_DESTSTARTVOL_TEXT           1764
#define IDC_STATIC_SRCSTARTLABEL        1765
#define IDC_STATIC_DESTSTARTLABEL       1766
#define IDC_STATIC_DESTENDLABEL         1767
#define IDC_STATIC_SRCENDLABEL          1768
#define IDC_COMBO_PDF                   1772
#define IDC_CHECK_DITHER                1773
#define IDC_SPKEYS_CONTROL              1775
#define IDC_SPKEYS_SPACE                1776
#define IDC_SPKEYS_DELETE               1777
#define IDC_SPKEYS_RETURN               1778
#define IDC_SPKEYS_BACKSPACE            1779
#define IDC_SPKEYS_TAB                  1780
#define IDC_DESCRLABEL                  1780
#define IDC_SPKEYS_INTRO                1781
#define IDC_SPKEYS_NEXTPAG              1782
#define IDC_CMBPROGRAM                  1782
#define IDC_SPKEYS_PREVPAG              1783
#define IDC_LISTPARAM                   1783
#define IDC_SLIDERPARAM                 1784
#define IDC_SPINPARAM                   1785
#define IDC_SHOWPATTERNAME              1786
#define IDC_REPLACEMAC                  1787
#define IDC_NEWMACBEFORE                1788
#define IDC_VOLLABEL                    1789
#define IDC_NEWMACAFTER                 1789
#define IDC_OUTPUTFILE                  1790
#define IDC_OUTPUTCLIPBOARD             1791
#define IDC_PSYCLEVSTBRIDGE             1791
#define IDC_ACCESS_EXCLUSIVE            1791
#define IDC_MIDI_KEYBOARD               1791
#define IDC_HEADER_NAMES                1791
#define IDC_LINESTART                   1792
#define IDC_OUTPUTSAMPLE                1793
#define IDC_CHECKTWK                    1794
#define IDC_FILTERNOTE                  1795
#define IDC_FILTERINS                   1796
#define IDC_FILTERMAC                   1797
#define IDC_FILTERCMD                   1798
#define IDAPPLY                         1800
#define ID_REPLACE                      1800
#define IDD_REPLACE                     1800
#define IDC_APPLYTOSONG                 1801
#define IDC_APPLYTOPATTERN              1802
#define IDC_LOCKINST                    1802
#define IDC_APPLYTOBLOCK                1803
#define IDD_SEARCH                      1804
#define IDC_JBRIDGE                     1805
#define IDC_ENABLEBRIDGE                1806
#define IDC_CPU_PERF                    1808
#define IDC_ACCESS_SHARED               1809
#define IDC_MIDI_SEQUENCED              1809
#define IDC_HEADER_HEADER               1809
#define IDC_WAVEOUT_BITDEPTH            1810
#define IDC_WASAPI_DEVICE               1812
#define IDC_WASAPI_SAMPLERATE_COMBO     1813
#define IDC_WASAPI_BUFFERSIZE_COMBO     1814
#define IDC_WASAPI_LATENCY              1815
#define IDC_MAC_NAME                    1817
#define IDC_SCAN_NEW                    1818
#define IDC_HOLD                        1819
#define IDC_CONTRIBUTORS                1820
#define IDC_USERPRESETS_EDIT            1821
#define IDC_TEXT_CLOCKDEVICE            1822
#define IDC_LUASCRIPTS_EDIT             1822
#define IDC_TEXT_HEADROOM               1823
#define IDC_LADSPAEDIT                  1823
#define IDC_SAVESETTINGS_ON             1824
#define IDC_NAMES_SHARE                 1825
#define IDC_NAMES_INDIVIDUAL            1826
#define IDC_TRACKLIST                   1827
#define IDC_TRACKEDIT                   1828
#define IDC_COPY_BUTTON                 1829
#define IDC_SHOW_MASTER                 1830
#define IDC_MASTERDLG_VULEFT            1831
#define IDC_MASTERDLG_VURIGHT           1832
#define IDC_DEFAULTC4                   1833
#define IDC_LOAD_NEW_BLITZ              1837
#define IDC_RECORD_USE_PSYDIR           1838
#define IDC_CHK_CHANMAP_0               1839
#define IDC_CHK_CHANMAP_255             2095
#define IDC_SRCDEST_LABEL               2098
#define IDC_AUTOWIRE                    2099
#define IDC_UNSELECT                    2100
#define IDC_NUMBER_THREADS              2103
#define IDC_XMINST_TAB                  2104
#define IDC_GROUP_ENV                   2105
#define IDC_SET_ALL_SAMPLE              2107
#define IDC_INCREASEOCT                 2108
#define IDC_DECREASEOCT                 2109
#define IDC_SETDEFAULT                  2110
#define IDC_INST_ADDTEN                 2111
#define IDC_DECREASENOTE                2111
#define IDC_INST_ADDONE                 2112
#define IDC_INCREASENOTE                2112
#define IDC_INST_DECONE                 2113
#define IDC_INST_DECTEN                 2114
#define IDC_SLIDERVOL                   2116
#define IDC_PANSLIDER                   2117
#define IDC_SLIDERFINE                  2118
#define IDC_SLIDER_AMPATT               2119
#define IDC_SLIDER_AMPDEC               2120
#define IDC_SLIDER_AMPSUS               2121
#define IDC_SLIDER_AMPREL               2122
#define IDC_SLIDER_FILATT               2123
#define IDC_SLIDER_FILDEC               2124
#define IDC_SLIDER_FILSUS               2125
#define IDC_SLIDER_FILREL               2126
#define IDC_SLIDER_FILAMT               2127
#define IDC_SLIDER_FCUT                 2128
#define IDC_SLIDER_FRES                 2129
#define IDC_COMBOFILTER                 2130
#define IDC_FINELABEL                   2131
#define IDC_ENV_CARRY                   2132
#define IDC_EDITMAPPING                 2133
#define IDC_INS_SHIFTMOVE               2135
#define IDC_INDIV_NOTE                  2136
#define IDC_INDIV_SAMPLE                2137
#define IDC_INSTLIST_SAMPLES            2138
#define IDC_SAMPLESLIST                 2139
#define IDC_NOTELIST                    2140
#define IDC_NOTEMAP_LIST                2141
#define IDC_RADIO_EDIT                  2142
#define IDC_RADIO_SHOW                  2143
#define IDC_SAMPLIST_INSTR              2144
#define IDC_SPIN_TEMPO                  2145
#define IDC_EDIT_TEMPO                  2146
#define IDC_SPIN_LPB                    2147
#define IDC_EDIT_LPB                    2148
#define IDC_SPIN_TPB                    2149
#define IDC_EDIT_TPB                    2150
#define IDC_EDIT_EXTRATICK              2151
#define IDC_SPIN_EXTRATICK              2152
#define IDC_EDIT_REALTPB                2153
#define IDC_EDIT_REALTEMPO              2154
#define IDC_EDIT_TITLE                  2155
#define IDC_MAP_SELECT_ALL              2156
#define IDC_MAP_SELECT_NONE             2157
#define IDC_MAP_SELECT_OCTAVE           2158
#define IDC_PAT_NUMLINES                2159
#define IDC_INSTR_SETSAMPLES_0          2160
#define IDC_INSTR_SETSAMPLES_255        2415
#define IDC_SAMPINST_CMB                2416
#define IDC_VIRTINSTCMB                 2417
#define IDC_LOCKINSTCMB                 2418
#define IDC_VIRTMACCOMBO                2419
#define IDC_VIRTINST                    2420
#define IDC_VIRTINSCOMBO                2421
#define IDC_SEARCHINSTCOMB              2422
#define IDC_SEARCHMACHCOMB              2423
#define IDC_REPLINSTCOMB                2424
#define IDC_REPLMACHCOMB                2425
#define IDC_SEARCHNOTECOMB              2426
#define IDC_CH_INCLUDEPAT               2427
#define IDC_R_SHOWPLAYALL               2428
#define IDC_FILTERTYPE1                 2429
#define IDC_FILTERTYPE2                 2430
#define IDC_REPLTWEAKCHECK              2430
#define IDC_FILTERTYPE3                 2431
#define IDC_LINEARSLIDE                 2431
#define IDC_FILTERTYPE4                 2432
#define IDC_FILTERTYPE5                 2433
#define IDC_FILTERTYPE6                 2434
#define IDC_FILTERTYPE7                 2435
#define IDC_FILTERTYPE8                 2436
#define PSYC_ENVELOPE_CHANGED           4096
#define SAVEWAV_RECORDEND               4097
#define ID_FILE_LOADSONG                32775
#define ID_FILE_IMPORT_XMFILE           32777
#define ID_FILE_IMPORT_ITFILE           32778
#define ID_FILE_SONGPROPERTIES          32779
#define ID_FILE_RECENT_01               32780
#define ID_FILE_RECENT_02               32781
#define ID_FILE_RECENT_03               32782
#define ID_FILE_RECENT_04               32783
#define ID_FILE_RECENT_NONE             32784
#define ID_MACHINEVIEW                  32786
#define ID_PATTERNVIEW                  32787
#define ID_NEWMACHINE                   32789
#define ID_VIEW_INSTRUMENTEDITOR        32790
#define ID_CONFIGURATION_FREEAUDIO      32792
#define ID_CONFIGURATION_SETTINGS       32793
#define ID_CPUPERFORMANCE               32796
#define ID_MIDI_MONITOR                 32797
#define ID_PSYHELP                      32799
#define ID_ABOUTPSYCLE                  32800
#define ID_HELP_SALUDOS                 32801
#define ID_RECORDB                      32803
#define ID_BARPLAY                      32804
#define ID_BUTTONPLAYSEQBLOCK           32805
#define ID_BARSTOP                      32806
#define ID_AUTOSTOP                     32807
#define ID_MACHINE_COMMAND              32814
#define ID_PARAMETERS_SHOWPRESET        32819
#define ID_POP_CUT                      32823
#define ID_POP_COPY                     32824
#define ID_POP_PASTE                    32825
#define ID_POP_INTERPOLATE              32826
#define ID_POP_CHANGEGENERATOR          32827
#define ID_POP_CHANGEINSTRUMENT         32828
#define ID_POP_TRANSPOSE1               32829
#define ID_POP_TRANSPOSE12              32830
#define ID_POP_TRANSPOSE_12             32831
#define ID_POP_PATTENPROPERTIES         32832
#define ID_POP_MIXPASTE                 32833
#define ID_POP_TRANSPOSE_1              32834
#define ID_SELECTION_AMPLIFY            32836
#define ID_SELECTION_REVERSE            32837
#define ID_SELECTION_FADEIN             32838
#define ID_SELECTION_FADEOUT            32839
#define ID_SELECTION_NORMALIZE          32840
#define ID_SELECTION_REMOVEDC           32841
#define ID_SELECCION_ZOOMOUT            32844
#define ID_SELECTION_SHOWALL            32845
#define ID_EDIT_DELETE                  32849
#define ID_CONVERT_MONO                 32850
#define ID_CONVERT_STEREO               32851
#define ID_INDICATOR_SIZE               32853
#define ID_INDICATOR_MODE               32854
#define ID_INDICATOR_SEL                32855
#define IDS_COULDNT_INITIALIZE_TIMER    32880
#define IDS_SONG_SAVED                  32881
#define IDS_ARE_YOU_SURE                32882
#define ID_POP_BLOCK_SWINGFILL          32885
#define ID_POP_TRACK_SWINGFILL          32886
#define ID_EDIT_MIXPASTE                32890
#define ID_FILE_SAVEAUDIO               32894
#define ID_HELP_WHATSNEW                32895
#define ID_HELP_README                  32896
#define ID_HELP_TWEAKING                32897
#define ID_HELP_KEYBTXT                 32898
#define ID_BARREC                       32902
#define ID_POP_DELETE                   32903
#define ID_FILE_REVERT                  32905
#define ID_CONFIGURATION_OPENONLYVISUALCONFIG 32906
#define ID_CONFIGURATION_OPENONLYKEYBOARDCONFIG 32907
#define ID_CONFIGURATION_OPENONLYDIRECTORIESCONFIG 32908
#define ID_CONFIGURATION_OPENONLYINPUTOUTPUTCONFIG 32909
#define ID_CONFIGURATION_OPENONLYMIDIINPUTCONFIG 32910
#define ID_VIEW_SONGBAR                 32911
#define ID_VIEW_MACHINEBAR              32912
#define ID_VIEW_SEQUENCER               32913
#define ID_VIEW_SEQUENCERBAR            32914
#define ID_CONFIGURATION_LOOPPLAYBACK   32920
#define ID_BARPLAYFROMSTART             32921
#define ID_VIEW_LoggingWindow           32927
#define ID_EDIT_CROP                    32929
#define ID_VIEW_MIXER                   32934
#define ID_POP_BLOCKSWITCH              32940
#define ID__ENV_ADDNEWPOINT             32956
#define ID__ENV_SETSUSTAINBEGIN         32957
#define ID__ENV_SETSUSTAINEND           32958
#define ID__ENV_SETLOOPSTART            32959
#define ID__ENV_SETLOOPEND              32960
#define ID__ENV_REMOVEPOINT             32961
#define ID__ENV_REMOVESUSTAIN           32962
#define ID__ENV_REMOVELOOP              32963
#define ID__ENV_REMOVEENVELOPE          32964
#define ID_POP_INTERPOLATE_CURVE        32999
#define ID_SELECCION_ZOOMIN             33000
#define ID_SELECTION_ZOOMSEL            33002
#define ID_PASTE_MIX                    33004
#define ID_PASTE_OVERWRITE              33005
#define ID_PASTE_CROSSFADE              33006
#define ID_EDIT_SNAPTOZERO              33007
#define ID_SELECTION_INSERTSILENCE      33009
#define ID_WAVED_PLAY                   33012
#define ID_WAVED_PLAYFROMSTART          33013
#define ID_WAVED_STOP                   33014
#define ID_WAVED_RELEASE                33017
#define ID_POPUP_ZOOMSEL                33028
#define ID_POPUP_CUT                    33029
#define ID_POPUP_COPY                   33030
#define ID_POPUP_PASTE                  33031
#define ID_POPUP_DELETE                 33032
#define ID_POPUP_SETLOOPSTART           33035
#define ID_POPUP_SETLOOPEND             33036
#define ID_POPUP_ZOOMIN                 33039
#define ID_POPUP_ZOOMOUT                33040
#define ID_FASTFORWARD                  33041
#define ID_REWIND                       33043
#define ID_WAVED_REWIND                 33044
#define ID_WAVED_FASTFORWARD            33045
#define ID_POPUP_SELECTIONTOLOOP        33047
#define ID_ABOUT_EXTENDEDINFO           33060
#define ID_OPERATIONS_ENABLED           33062
#define ID_OPERATIONS_BYPASSED          33063
#define ID_VIEWS_PARAMETERLIST          33064
#define ID_VIEWS_BANKMANAGER            33065
#define ID_VIEWS_MIDICHANNELS           33066
#define ID_PROGRAMS_RANDOMIZEPROGRAM    33068
#define ID_COMBO_PRG                    33075
#define ID_PROGRAMS_OPENPRESET          33077
#define ID_PROGRAMS_SAVEPRESET          33078
#define ID_ABOUT_ABOUTMAC               33080
#define ID_SELECTBANK_0                 33100
#define ID_SELECTPROGRAM_0              33200
#define ID_PROGRAMMORE                  34200
#define ID_PROGRAMLESS                  34201
#define ID_VIEWS_SHOWTOOLBAR            34206
#define ID__TRANSFORMPATTERN            34207
#define ID_POP_TRANSFORMPATTERN         34209
#define ID_EXPORT                       34211
#define ID__SEQPASTEBELOW               34232
#define ID__SEQSORT                     34233
#define ID__SEQCHANGEPOS                34235
#define ID__SEQRENAME                   34236
#define ID__SEQCLEAR                    34237
#define ID_CONNECTIONS_CONNECTIONN      34245
#define ID_CONNECTTO_MACHINEN           34246
#define ID_CONTEXTMENU_UNDO             34256
#define ID_CONTEXTMENU_REDO             34257
#define ID_PROGRAMS_RESETDEFAULT        34268
#define ID_CONFIGURATION_ENABLEAUDIO    34276
#define ID_POP_ADDNEWTRACK              34281
#define IDC_FULL_SCREEN                 34283
#define ID_CONFIGURATION_REGENERATEPLUGINCACHE 34284
#define ID_PARAMETERS_VIEWS_RELOAD      34286
#define ID_VISUALREPRESENTATION_SAMPLEHOLD 34289
#define ID_VISUALREPRESENTATION_SPLINE  34290
#define ID_VISUALREPRESENTATION_SINC    34291
#define ID_ACCEL_SAMPLER                34295
#define ID_ACCEL_SAMPULSE               34296
#define ID_ACCEL_WAVE                   34297
#define ID_ACCEL_GEN                    34298
#define ID_ACCEL_VOL                    34299
#define ID_ACCEL_PAN                    34300
#define ID_ACCEL_FILTER                 34301
#define ID_WAVEED_WAVEMIN               34305
#define ID_WAVEED_WAVEPLUS              34306
#define ID_WAVEEDIT_COMBO_WAV           34307
#define ID_IMPORT_MACHINES              34313
#define ID_EXPORT_PATTERNS              34315
#define ID_EXPORT_INSTRUMENTS           34316
#define ID_EXPORT_MODULE                34317
#define ID_IMPORT_PATTERNS              34318
#define ID_IMPORT_INSTRUMENTS           34319
#define ID_HELP_LUASCRIPT               34320
#define ID_CONTEXTMENU_REPLACEMACHINE   34321
#define ID_CONTEXTMENU_CLONEMACHINE     34322
#define ID_CONTEXTMENU_INSERTEFFECTHERE 34323
#define ID_CONTEXTMENU_INSERTEFFECTBEFORE 34324
#define ID_CONTEXTMENU_DELETEMACHINE    34325
#define ID_CONTEXTMENU_INSERTEFFECTAFTER 34326
#define ID_CONTEXTMENU_OPENPARAMETERS   34327
#define ID_CONTEXTMENU_OPENPROPERTIES   34328
#define ID_CONTEXTMENU_MUTE             34329
#define ID_CONTEXTMENU_SOLO             34330
#define ID_CONTEXTMENU_BYPASS           34331
#define ID_POPUPMAC_OPENPARAMETERS      34332
#define ID_POPUPMAC_OPENPROPERTIES      34333
#define ID_POPUPMAC_REPLACEMACHINE      34334
#define ID_POPUPMAC_CLONEMACHINE        34335
#define ID_POPUPMAC_INSERTEFFECTBEFORE  34336
#define ID_POPUPMAC_INSERTEFFECTAFTER   34337
#define ID_POPUPMAC_DELETEMACHINE       34338
#define ID_POPUPMAC_MUTE                34339
#define ID_POPUPMAC_SOLO                34340
#define ID_POPUPMAC_BYPASS              34341
#define ID_CONNECTTO_MACHINE0           34342
#define ID_CONNECTTO_MACHINE64          34406
#define ID_CONNECTIONS_CONNECTION0      34407
#define ID_CONNECTIONS_CONNECTION24     34431
#define ID_WAVEED_LOAD                  34433
#define ID_WAVEED_SAVE                  34434
#define ID_POPUPMAC_OPENBANKMANAGER     34435
#define ID_EDIT_SEARCHANDREPLACE        34436
#define ID__UNSETLOOP                   34437
#define ID__UNSETSUSTAINLOOP            34438
#define ID__SETSUSTAINSTART             34439
#define ID__SETSUSTAINEND               34440
#define ID__SETSUSTANTOSELECTION        34441
#define ID_DYNAMIC_MENUS_START          34442
#define ID_VIEWS_PARAMETERMAP           34443
#define ID_DYNAMIC_MENUS_END            35442
#define ID_DYNAMIC_CONTROLS_BEGIN       35443
#define ID_DYNAMIC_CONTROLS_LAST        45443
#define WM_USER_RELOAD_LUA              45444
#define ID_TEXT                         65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        346
#define _APS_NEXT_COMMAND_VALUE         34444
#define _APS_NEXT_CONTROL_VALUE         2432
#define _APS_NEXT_SYMED_VALUE           65
#endif
#endif
