static const AVInputFormat * const demuxer_list[] = {
    &ff_aac_demuxer,
    &ff_ac3_demuxer,
    &ff_ape_demuxer,
    &ff_asf_demuxer,
    &ff_bink_demuxer,
    &ff_binka_demuxer,
    &ff_caf_demuxer,
    &ff_eac3_demuxer,
    &ff_flac_demuxer,
    &ff_mov_demuxer,
    &ff_mp3_demuxer,
    &ff_mpc_demuxer,
    &ff_mpc8_demuxer,
    &ff_ogg_demuxer,
    &ff_oma_demuxer,
    &ff_smacker_demuxer,
    &ff_spdif_demuxer,
    &ff_tak_demuxer,
    &ff_wav_demuxer,
    &ff_xmv_demuxer,
    &ff_xwma_demuxer,
    NULL };
