//just add at the end of the list new extensions
EXTENSION(mptm)
EXTENSION(mod)          // OpenMPT & XMP
EXTENSION(s3m)          // OpenMPT & XMP
EXTENSION(xm)           // OpenMPT & XMP
EXTENSION(it)           // OpenMPT & XMP
EXTENSION(669)          // OpenMPT & XMP
EXTENSION(amf)          // OpenMPT & XMP
EXTENSION(ams)
EXTENSION(c67)
EXTENSION(dbm)          // OpenMPT & XMP & VGMStream: Konami MTA2
EXTENSION(digi)
EXTENSION(dmf)
EXTENSION(dsm)
EXTENSION(dtm)
EXTENSION(far)          // OpenMPT & XMP
EXTENSION(imf)          // OpenMPT & XMP & VGMStream: MPEG
EXTENSION(ice)
EXTENSION(j2b)
EXTENSION(m15)
EXTENSION(mdl)          // OpenMPT & XMP
EXTENSION(med)          // OpenMPT & XMP & UADE: Octa-MED & VGMStream
EXTENSION(mms)          // OpenMPT & UADE: MultiMedia_Sound
EXTENSION(mt2)
EXTENSION(mtm)          // OpenMPT & XMP
EXTENSION(nst)
EXTENSION(okt)          // OpenMPT & XMP & UADE: Oktalyzer
EXTENSION(plm)
EXTENSION(psm)          // OpenMPT & XMP & ZXTune: Pro Sound Maker
EXTENSION(pt36)
EXTENSION(ptm)          // OpenMPT & XMP
EXTENSION(sfx)          // OpenMPT & XMP & UADE: Sound-FX & VGMStream: FMOD FSB
EXTENSION(sfx2)
EXTENSION(st26)
EXTENSION(stk)          // OpenMPT & XMP
EXTENSION(stm)          // OpenMPT & XMP & VGMStream
EXTENSION(stp)          // ZXTune: Sound Tracker Pro
EXTENSION(ult)          // OpenMPT & XMP
EXTENSION(wow)
EXTENSION(gdm)          // OpenMPT & XMP
EXTENSION(mo3)
EXTENSION(oxm)
EXTENSION(umx)          // OpenMPT & XMP
EXTENSION(xpk)
EXTENSION(ppm)
EXTENSION(mmcmp)
EXTENSION(hvl)
EXTENSION(ahx)          // Hively & VGMStream: CRI AHX
EXTENSION(bp)           // SoundMon & UAE: SoundMon2.0
EXTENSION(ym)           // ZXTune: ST-Sound
EXTENSION(dsym)         // OpenMPT & XMP
EXTENSION(fmt)
EXTENSION(mus)          // OpenMPT: ? & Sidplay: ? & UADE: UFO & NEZplug: FAC SoundTracker & VGMStream: Krome MUSC
EXTENSION(stx)          // OpenMPT & XMP & VGMStream
EXTENSION(symmod)
EXTENSION(smod)
EXTENSION(fc)
EXTENSION(rsid)
EXTENSION(psid)
EXTENSION(v2m)
EXTENSION(sndh)
EXTENSION(sc68)
EXTENSION(hsc)
EXTENSION(sng)          // Adlib: ? : & GoatTracker & UADE: ZoundMonitor & VGMStream: Electronic Arts SCHl
EXTENSION(wlf)
EXTENSION(adlib)
EXTENSION(a2m)
EXTENSION(amd)
EXTENSION(bam)
EXTENSION(cmf)
EXTENSION(d00)
EXTENSION(dfm)
EXTENSION(hsp)
EXTENSION(ksm)          // Adlib: Ken's Silverman & Ken & XMP
EXTENSION(mad)          // Adlib & VGMStream: Electronic Arts SCHl
EXTENSION(ims)          // Adlib: Midi/IMS & XMP & UADE: ImagesMusicSystem
EXTENSION(mdi)
EXTENSION(mid)
EXTENSION(sci)
EXTENSION(laa)
EXTENSION(mkj)
EXTENSION(cff)
EXTENSION(dmo)
EXTENSION(mtk)
EXTENSION(rad)          // Adlib & VGMStream
EXTENSION(rac)
EXTENSION(raw)
EXTENSION(sat)
EXTENSION(sa2)
EXTENSION(xad)
EXTENSION(bmf)
EXTENSION(lds)
EXTENSION(m)
EXTENSION(rol)
EXTENSION(xsm)
EXTENSION(dro)
EXTENSION(msc)
EXTENSION(rix)
EXTENSION(adl)
EXTENSION(jbm)
EXTENSION(got)
EXTENSION(vgm)
EXTENSION(vgz)
EXTENSION(sop)
EXTENSION(hsq)
EXTENSION(sqx)
EXTENSION(sdb)
EXTENSION(agd)
EXTENSION(ha2)
EXTENSION(bp3)          // SoundMon & UAE: SoundMon2.2
EXTENSION(sap)          // ASAP & VGMStream
EXTENSION(cmc)
EXTENSION(cm3)
EXTENSION(cmr)
EXTENSION(cms)
EXTENSION(dmc)
EXTENSION(dlt)
EXTENSION(mpt)
EXTENSION(mpd)
EXTENSION(rmt)
EXTENSION(tmc)
EXTENSION(tm8)
EXTENSION(tm2)
EXTENSION(tfm)
EXTENSION(mp3)          // MP3 & VGMStream
EXTENSION(flac)
EXTENSION(ogg)
EXTENSION(ay)           // Ayfly & GME & NEZplug & ZXTune: AY/Emul
EXTENSION(vtx)          // ZXTune: Vortex Project
EXTENSION(psg)          // ZXTune: Programmable Sound Generator
EXTENSION(asc)          // ZXTune: ASC Sound Master
EXTENSION(pt1)          // ZXTune: Pro Tracker
EXTENSION(pt2)          // ZXTune: Pro Tracker
EXTENSION(pt3)          // ZXTune: Pro Tracker
EXTENSION(stc)          // ZXTune: Sound Tracker
EXTENSION(sqt)          // AyFly: ? & UADE: Quartet_PSG & ZXTune: SQ-Tracker
EXTENSION(psc)          // ZXTune: Pro Sound Creator
EXTENSION(gbs)          // GBSPlay & GME & NEZplug
EXTENSION(gbr)          // GBSPlay & NEZplug
EXTENSION(gb)
EXTENSION(gym)
EXTENSION(hes)          // GME & NEZplug
EXTENSION(kss)          // KSS & GME & NEZplug
EXTENSION(nsf)          // GME & NEZplug
EXTENSION(nsfe)         // GME & NEZplug
EXTENSION(spc)
EXTENSION(sunvox)		// SunVox
EXTENSION(mdx)          // MDX
EXTENSION(rk)           // UADE: CustomMade
EXTENSION(s98)
EXTENSION(aps)          // UADE: AProSys
EXTENSION(ast)          // UADE: ActionAmics & VGMStream: Nintendo AST
EXTENSION(adpcm)        // UADE: ADPCM_mono & VGMStream: RIFF WAVE
EXTENSION(amc)          // UADE: AM-Composer
EXTENSION(abk)          // UADE & XMP: AMOS & VGMStream: Electronic Arts BNK
EXTENSION(hot)          // UADE: Anders_0land
EXTENSION(aam)          // UADE: ArtAndMagic
EXTENSION(alp)          // UADE: Alcatraz_Packer
EXTENSION(bye)          // UADE: Andrew_Parton
EXTENSION(aon)          // UADE: ArtOfNoise
EXTENSION(ash)          // UADE: Ashley_Hogg
EXTENSION(adsc)         // UADE: AudioSculpture
EXTENSION(bss)          // UADE: BeathovenSynthesizer
EXTENSION(bd)           // UADE: BenDaglish
EXTENSION(bds)          // UADE: BenDaglish-SID
EXTENSION(uds)          // UADE: BladePacker
EXTENSION(kris)         // UADE: ChipTracker
EXTENSION(cin)          // UADE: Cinemaware
EXTENSION(core)         // UADE: CoreDesign
EXTENSION(cus)          // UADE: custom
EXTENSION(cm)           // UADE: CustomMade
EXTENSION(dz)           // UADE: DariusZendeh
EXTENSION(dl)           // UADE: DaveLowe
EXTENSION(dl_deli)      // UADE: DaveLowe_Deli
EXTENSION(dln)          // UADE: DaveLoweNew
EXTENSION(dh)           // UADE: DavidHanney
EXTENSION(dw)           // UADE: DavidWhittaker
EXTENSION(dm)           // UADE: DeltaMusic1.3
EXTENSION(dm2)          // UADE: DeltaMusic2.0
EXTENSION(dsr)          // UADE: Desire
EXTENSION(dsc)          // UADE: DigitalSonixChrome
EXTENSION(dss)          // UADE: DigitalSoundStudio
EXTENSION(dns)          // UADE: DynamicSynthesizer
EXTENSION(ems)          // UADE: EMS & EMS-6
EXTENSION(ex)           // UADE: FashionTracker
EXTENSION(fred)         // UADE: Fred
EXTENSION(gray)         // UADE: FredGray
EXTENSION(bsi)          // UADE: FutureComposer-BSI
EXTENSION(fp)           // UADE: FuturePlayer
EXTENSION(fw)           // UADE: ForgottenWorlds_Game
EXTENSION(glue)         // UADE: GlueMon
EXTENSION(gmc)          // UADE: GMC
EXTENSION(ea)           // UADE: EarAche
EXTENSION(hd)           // UADE: HowieDavies
EXTENSION(hipc)         // UADE: JochenHippel-CoSo
EXTENSION(emod)         // UADE & XMP: QuadraComposer
EXTENSION(dum)          // UADE: Infogrames
EXTENSION(is)           // UADE: InStereo
EXTENSION(is20)         // UADE: InStereo2.0
EXTENSION(jam)          // UADE: JamCracker
EXTENSION(jmf)          // UADE: JankoMrsicFlogel
EXTENSION(js)           // UADE: Janne_Salmijarvi_Optimizer
EXTENSION(jb)           // UADE: JasonBrooke
EXTENSION(jpn)          // UADE: JasonPage
EXTENSION(jpo)          // UADE: JasonPage_JP & UADE: SteveTurner
EXTENSION(jt)           // UADE: JeroenTel
EXTENSION(jo)           // UADE: JesperOlsen
EXTENSION(hip)          // UADE: JochenHippel
EXTENSION(hip7)         // UADE: JochenHippel-7V
EXTENSION(hst)          // UADE: Jochen_Hippel_ST
EXTENSION(kim)          // UADE: Kim_Christensen
EXTENSION(kh)           // UADE: KrisHatlelid
EXTENSION(pt)           // UADE: Laxity
EXTENSION(lme)          // UADE: LegglessMusicEditor
EXTENSION(mon)          // UADE: ManiacsOfNoise
EXTENSION(mfp)          // UADE & XMP: MagneticFieldsPacker
EXTENSION(hn)           // UADE: MajorTom
EXTENSION(mc)           // UADE: Mark_Cooksey
EXTENSION(mco)          // UADE: Mark_Cooksey_Old
EXTENSION(mk2)          // UADE: MarkII
EXTENSION(avp)          // UADE: MartinWalker
EXTENSION(max)          // UADE: Maximum_Effect
EXTENSION(midi)         // UADE: MIDI-Loriciel
EXTENSION(md)           // UADE: MikeDavies
EXTENSION(mosh)         // UADE: Mosh_Packer
EXTENSION(mmdc)         // UADE: MMDC
EXTENSION(dmu)          // UADE: Mugician
EXTENSION(dmu2)         // UADE: MugicianII
EXTENSION(ma)           // UADE: MusicAssembler
EXTENSION(mm4)          // UADE: MusicMaker-4V
EXTENSION(mm8)          // UADE: MusicMaker-8V
EXTENSION(npp)          // UADE: Nick_Pelling_Packer
EXTENSION(ntp)          // UADE & XMP: NovoTradePacker
EXTENSION(two)          // UADE: NTSP-system
EXTENSION(one)          // UADE: onEscapee
EXTENSION(dat)          // UADE: PaulRobotham
EXTENSION(ps)           // UADE: PaulShields
EXTENSION(snk)          // UADE: PaulSummers
EXTENSION(pat)          // UADE: Paul_Tonge
EXTENSION(pvp)          // UADE: PeterVerswyvelen
EXTENSION(pap)          // UADE: PierreAdane
EXTENSION(pn)           // UADE: Pokeynoise
EXTENSION(psa)          // UADE: ProfessionalSoundArtists
EXTENSION(puma)         // UADE: PumaTracker
EXTENSION(rj)           // UADE: RichardJoseph
EXTENSION(rjp)          // UADE: RichardJoseph_Player
EXTENSION(riff)         // UADE: RiffRaff & XMP: Galaxy Music System 4.0
EXTENSION(rh)           // UADE: RobHubbard
EXTENSION(rho)          // UADE: RobHubbard_ST
EXTENSION(scumm)        // UADE: SCUMM
EXTENSION(scn)          // UADE: SeanConnolly
EXTENSION(scr)          // UADE: SeanConran
EXTENSION(sid1)         // UADE: SIDMon1.0
EXTENSION(sid2)         // UADE: SIDMon2.0
EXTENSION(mok)          // UADE: Silmarils
EXTENSION(sa)           // UADE: SonicArranger
EXTENSION(smus)         // UADE: SonixMusicDriver
EXTENSION(spl)          // UADE: SoundProgrammingLanguage
EXTENSION(sc)           // UADE: SoundControl & VGMStream
EXTENSION(psf)          // UADE: SoundFactory & Highly Experimental & VGMStream
EXTENSION(tw)           // UADE: SoundImages
EXTENSION(sm)           // UADE: SoundMaster & Ken
EXTENSION(sm2)          // UADE: SoundMaster & VGMStream
EXTENSION(sm3)          // UADE: SoundMaster & VGMStream: Ubisoft SBx
EXTENSION(smpro)        // UADE: SoundMaster
EXTENSION(sjs)          // UADE: SoundPlayer
EXTENSION(jd)           // UADE: Special-FX
EXTENSION(doda)         // UADE: Special-FX_ST
EXTENSION(sas)          // UADE: SpeedyA1System
EXTENSION(ss)           // UADE: SpeedySystem
EXTENSION(sb)           // UADE: SteveBarrett
EXTENSION(sun)          // UADE: SUN-Tronic
EXTENSION(syn)          // UADE: Synth
EXTENSION(sdr)          // UADE: SynthDream
EXTENSION(osp)          // UADE: SynthPack
EXTENSION(synmod)       // UADE: SynTracker
EXTENSION(tcb)          // UADE: TCB_Tracker
EXTENSION(mdst)         // UADE: TFMX_ST
EXTENSION(thm)          // UADE: ThomasHermann
EXTENSION(tmk)          // UADE: TimeTracker
EXTENSION(tits)         // UADE: Titanics_Packer
EXTENSION(tme)          // UADE: TheMusicalEnlightenment
EXTENSION(sg)           // UADE: TomyTracker
EXTENSION(dp)           // UADE: Tronic
EXTENSION(vss)          // UADE: VoodooSupremeSynthesizer
EXTENSION(wb)           // UADE: WallyBeben & VGMStream: Triangle Service .WB
EXTENSION(ml)           // UADE: MusiclineEditor
EXTENSION(agi)          // UADE: Sierra-AGI
EXTENSION(tpu)          // UADE: DirkBialluch
EXTENSION(qpa)          // UADE: Quartet
EXTENSION(qts)          // UADE: Quartet_ST & Quartet
EXTENSION(miniqsf)      // Highly Quixotic
EXTENSION(rar)          // archive
EXTENSION(minigsf)      // Highly Advanced
EXTENSION(7z)           // archive
EXTENSION(ymst)         // UADE: YMST
EXTENSION(wav)          // WAV
EXTENSION(sid)          // SidPlay & UADE: SidMon1
EXTENSION(mug)          // UADE: Mugician
EXTENSION(mso)          // UADE: Medley
EXTENSION(ptk)          // ProTrekkr
EXTENSION(mdy)          // Adlib: AdLib MIDI/IMS Format
EXTENSION(mcr)          // UADE: Mark_Cooksey_Old
EXTENSION(mgb)          // Gameboy Tracker: no known replay :(
EXTENSION(ixs)          // iXalance
EXTENSION(mgs)          // KSS
EXTENSION(bgm)          // KSS & VGMStream: Ogg Vorbis Encrypted
EXTENSION(opx)          // KSS
EXTENSION(mpk)          // KSS
EXTENSION(mbm)          // KSS
EXTENSION(sgc)          // NEZplug
EXTENSION(nsd)          // NEZplug
EXTENSION(pis)          // AdLib: Beni Tracker
EXTENSION(667)          // OpenMPT: Composer 667
EXTENSION(gtk)          // OpenMPT: Gramouf Tracker
EXTENSION(gt2)          // OpenMPT: Gramouf Tracker
EXTENSION(xmf)          // OpenMPT & XMP
EXTENSION(mdat)         // TFMX & UADE: TFMX
EXTENSION(ttt)          // TIATracker
EXTENSION(mini2sf)      // vio2sf
EXTENSION(gz)           // archive
EXTENSION(minissf)      // Highly Theoretical
EXTENSION(liq)          // XMP: Liquid Tracker
EXTENSION(minidsf)      // Highly Theoretical
EXTENSION(rtm)          // XMP: Real Tracker
EXTENSION(ssf)          // Highly Theoretical
EXTENSION(dsf)          // Highly Theoretical & DSD & VGMStream: Ocean DSF
EXTENSION(gsf)          // Highly Advanced & VGMStream: Electronic Arts SCHl
EXTENSION(2sf)          // vio2sf
EXTENSION(minipsf)      // Highly Experimental
EXTENSION(mgt)          // XMP: Megatracker
EXTENSION(psf2)         // Highly Experimental
EXTENSION(minipsf2)     // Highly Experimental
EXTENSION(fnk)          // XMP: Funktracker
EXTENSION(usf)          // LazyUSF
EXTENSION(miniusf)      // LazyUSF
EXTENSION(arch)         // XMP: Archimedes Tracker
EXTENSION(tf)           // UADE: TimFollin
EXTENSION(cust)         // UADE: custom
EXTENSION(snsf)         // Highly Competitive
EXTENSION(minisnsf)     // Highly Competitive
EXTENSION(coco)         // XMP: Coconizer
EXTENSION(prt)          // UADE: PreTracker
EXTENSION(mtr)          // Adlib: Master Tracker
EXTENSION(buz2)         // Buzzic 2
EXTENSION(txt)          // ZXTune: VortexTracker
EXTENSION(st1)          // ZXTune: Sound Tracker
EXTENSION(st3)          // ZXTune: Sound Tracker
EXTENSION(ts)           // ZXTune: TurboSound
EXTENSION(gtr)          // ZXTune: Global Tracker
EXTENSION(ayc)          // ZXTune: CPC AYC
EXTENSION(ftc)          // ZXTune: Fast Tracker
EXTENSION(as0)          // ZXTune: ASC Sound Master
EXTENSION(str)          // ZXTune: Sample Tracker & VGMStream: Electronic Arts SCHl
EXTENSION(chi)          // ZXTune: Chip Tracker
EXTENSION(sqd)          // ZXTune: SQ Digital Tracker
EXTENSION(dmm)          // ZXTune: Digital Music Maker
EXTENSION(pdt)          // ZXTune: ProDigi Tracker & VGMStream
EXTENSION(dst)          // ZXTune: Digital Studio
EXTENSION(et1)          // ZXTune: Extreme Tracker
EXTENSION(mtc)          // ZXTune: Multitrack Container
EXTENSION(cop)          // ZXTune: E-Tracker
EXTENSION(tfe)          // ZXTune: TFM Music Maker
EXTENSION(tf0)          // ZXTune: TFM Music Maker
EXTENSION(tfd)          // ZXTune: TurboFM
EXTENSION(tfc)          // ZXTune: TurboFM
EXTENSION(trd)          // ZXTune: TR-DOS
EXTENSION(szx)          // ZXTune: ZXState
EXTENSION(scl)          // ZXTune: SINCLAIR
EXTENSION(hrp)          // ZXTune: Hrust RiP
EXTENSION(zip)          // ZXTune: ZXZip
EXTENSION(bin)          // ZXTune: Hrust v1
EXTENSION(p)            // ZXTune: Hrust v2
EXTENSION(fdi)          // ZXTune: Full Disk Image
EXTENSION(hbt)          // ZXTune: Hobeta
EXTENSION(hrm)          // ZXTune: Hrum
EXTENSION(dsq)          // ZXTune: DataSqueezer
EXTENSION(esv)          // ZXTune: ESVCruncher
EXTENSION(tlz)          // ZXTune: TurboLZ
EXTENSION(tlzp)         // ZXTune: TurboLZ
EXTENSION(trs)          // ZXTune: Trush
EXTENSION(cc3)          // ZXTune: CodeCruncher
EXTENSION(gam)          // ZXTune: GamePacker
EXTENSION(gamplus)      // ZXTune: GamePacker
EXTENSION(lzs)          // ZXTune: ASCLZSPack
EXTENSION(msp)          // ZXTune: MicrospacePacker
EXTENSION(td0)          // ZXTune: TeleDisk Image
EXTENSION(pcd)          // ZXTune: Powerfull Code Decreaser
EXTENSION(soc)          // UADE: Jochen_Hippel_ST
EXTENSION(sog)          // UADE: Jochen_Hippel_ST
EXTENSION(mcmd)         // UADE: JochenHippel
EXTENSION(cba)          // OpenMPT
EXTENSION(a2t)			// Adlib: Adlib Tracker 2
EXTENSION(eup)          // Euphony
EXTENSION(etx)			// OpenMPT
EXTENSION(4v)           // Quartet
EXTENSION(fur)          // Furnace
EXTENSION(aac)          // AAC
EXTENSION(opus)         // Opus
EXTENSION(ftm)          // Furnace: Famitracker
EXTENSION(wv)           // WavPack
EXTENSION(dff)          // DSD
EXTENSION(208)          // VGMStream
EXTENSION(2dx9)         // VGMStream: Beatmania IIDX 2DX9
EXTENSION(2pfs)         // VGMStream
EXTENSION(3do)          // VGMStream
EXTENSION(4)            // VGMStream: Tiger Game.com .4
EXTENSION(800)          // VGMStream: Sony ADS
EXTENSION(9tav)         // VGMStream: Konami 9TAV
EXTENSION(aa3)          // VGMStream: Sony OpenMG audio
EXTENSION(aax)          // VGMStream: CRI AAX
EXTENSION(ac3)          // VGMStream: raw AC3
EXTENSION(acb)          // VGMStream: CRI HCA
EXTENSION(acm)          // VGMStream: InterPlay ACM
EXTENSION(acx)          // VGMStream: CRI ADX
EXTENSION(adm)          // VGMStream: Dragon Quest V .ADM raw
EXTENSION(adp)          // VGMStream: Nintendo .DTK raw
EXTENSION(adpcmx)       // VGMStream: AQUASTYLE ADPX
EXTENSION(ads)          // VGMStream: Sony ADS
EXTENSION(adw)          // VGMStream: RIFF WAVE (smpl looping)
EXTENSION(adx)          // VGMStream: CRI ADX
EXTENSION(afc)          // VGMStream: Nintendo AFC
EXTENSION(afs2)         // VGMStream: CRI HCA
EXTENSION(agsc)         // VGMStream: Retro Studios AGSC
EXTENSION(ahv)          // VGMStream: Amuze AHV
EXTENSION(ai)           // VGMStream
EXTENSION(aif)          // VGMStream: Apple AIFF-C
EXTENSION(aifc)         // VGMStream: Apple AIFF-C
EXTENSION(aiff)         // VGMStream: Apple AIFF
EXTENSION(aix)          // VGMStream: CRI AIX
EXTENSION(akb)          // VGMStream: Square Enix AKB
EXTENSION(an2)          // VGMStream
EXTENSION(ao)           // VGMStream: AlphaOgg .AO
EXTENSION(ap)           // VGMStream
EXTENSION(apc)          // VGMStream
EXTENSION(ape)          // VGMStream: Monkey's Audio
EXTENSION(as4)          // VGMStream: Electronic Arts 1SNh
EXTENSION(asbin)        // VGMStream
EXTENSION(asd)          // VGMStream: ASD
EXTENSION(asf)          // VGMStream: Electronic Arts SCHl
EXTENSION(asr)          // VGMStream: Paon KNON
EXTENSION(ass)          // VGMStream: SystemSoft .ASS
EXTENSION(at3)          // VGMStream: ATRAC3+
EXTENSION(at9)          // VGMStream: ATRAC9
EXTENSION(atsl)         // VGMStream: Ogg Vorbis KOVS
EXTENSION(atsl3)        // VGMStream
EXTENSION(atsl4)        // VGMStream: RIFF WAVE (smpl looping)
EXTENSION(atslx)        // VGMStream
EXTENSION(atx)          // VGMStream: RIFF WAVE (smpl looping)
EXTENSION(aud)          // VGMStream: Westwood Studios .AUD
EXTENSION(audio)        // VGMStream: Ogg Vorbis
EXTENSION(audio_data)   // VGMStream: Traveller's Tales AUDIO_DATA
EXTENSION(aus)          // VGMStream: Capcom AUS
EXTENSION(awb)          // VGMStream: CRI HCA
EXTENSION(awc)          // VGMStream: Rockstar AWC
EXTENSION(awd)          // VGMStream
EXTENSION(amb)          // VGMStream
EXTENSION(baf)          // VGMStream: Bizarre Creations .baf
EXTENSION(baka)         // VGMStream: Konami BAKA
EXTENSION(bank)         // VGMStream: FMOD FSB
EXTENSION(bar)          // VGMStream
EXTENSION(bcstm)        // VGMStream: Nintendo CSTM
EXTENSION(bcwav)        // VGMStream: Nintendo CWAV
EXTENSION(bfstm)        // VGMStream: Nintendo FSTM
EXTENSION(bfwav)        // VGMStream: Nintendo FWAV
EXTENSION(bg00)         // VGMStream: Cave BG00
EXTENSION(bgw)          // VGMStream: Square Enix .BGW
EXTENSION(bigrp)        // VGMStream: Inti Creates .BIGRP
EXTENSION(bik)          // VGMStream: RAD Game Tools Bink
EXTENSION(bika)         // VGMStream: RAD Game Tools Bink
EXTENSION(bik2)         // VGMStream
EXTENSION(binka)        // VGMStream: Bink Audio
EXTENSION(bk2)          // VGMStream: RAD Game Tools Bink
EXTENSION(blk)          // VGMStream: Ubisoft SBx
EXTENSION(bmdx)         // VGMStream
EXTENSION(bms)          // VGMStream: Nintendo CWAV
EXTENSION(bnk)          // VGMStream: Audiokinetic Wwise RIFF
EXTENSION(bnm)          // VGMStream: Ubisoft SBx
EXTENSION(bns)          // VGMStream: Nintendo BNS
EXTENSION(bnsf)         // VGMStream: Namco Bandai BNSF
EXTENSION(bo2)          // VGMStream: Legacy of Kain - Blood Omen 2 RKV GC
EXTENSION(brstm)        // VGMStream: Nintendo RSTM
EXTENSION(brstmspm)     // VGMStream: Nintendo RSTM
EXTENSION(brwav)        // VGMStream: Nintendo RWAV
EXTENSION(brwsd)        // VGMStream
EXTENSION(bsnd)         // VGMStream: id Software BSNF
EXTENSION(btsnd)        // VGMStream: Nintendo Wii U Menu Boot Sound
EXTENSION(bvg)          // VGMStream: Mattel Hyperscan KVAG
EXTENSION(bwav)         // VGMStream: Nintendo BWAV
EXTENSION(cads)         // VGMStream
EXTENSION(caf)          // VGMStream: Apple Core Audio Format
EXTENSION(cbd2)         // VGMStream
EXTENSION(cd)           // VGMStream
EXTENSION(cfn)          // VGMStream: tri-Crescendo CAF
EXTENSION(chk)          // VGMStream: Electronic Arts SCHl
EXTENSION(ckb)          // VGMStream: Cricket Audio CKB
EXTENSION(ckd)          // VGMStream: Ubisoft RAKI
EXTENSION(cks)          // VGMStream: Cricket Audio CKS
EXTENSION(cnk)          // VGMStream: Electronic Arts 1SNh
EXTENSION(cps)          // VGMStream: tri-Crescendo CPS
EXTENSION(csb)          // VGMStream
EXTENSION(csmp)         // VGMStream
EXTENSION(cwav)         // VGMStream: CompressWave .cwav
EXTENSION(cxs)          // VGMStream: tri-Crescendo CXS
EXTENSION(da)           // VGMStream: FFmpeg
EXTENSION(data)         // VGMStream
EXTENSION(dax)          // VGMStream
EXTENSION(dcs)          // VGMStream: In Utero DCS+WAV
EXTENSION(dct)          // VGMStream
EXTENSION(ddsp)         // VGMStream: .DDSP
EXTENSION(de2)          // VGMStream: Falcom .DEC RIFF
EXTENSION(dec)          // VGMStream: Falcom .DEC RIFF
EXTENSION(dic)          // VGMStream: Codemasters DIC1
EXTENSION(diva)         // VGMStream: Sega DIVA
EXTENSION(dmsg)         // VGMStream: FFmpeg
EXTENSION(dsb)          // VGMStream: Namco Bandai BNSF
EXTENSION(dsp)          // VGMStream: Nintendo THP
EXTENSION(dspw)         // VGMStream: Capcom DSPW
EXTENSION(dtk)          // VGMStream: Nintendo .DTK raw
EXTENSION(dvi)          // VGMStream: Konami DVI
EXTENSION(dyx)          // VGMStream
EXTENSION(e4x)          // VGMStream: Reflections XA30
EXTENSION(eam)          // VGMStream: Electronic Arts SCHl
EXTENSION(eas)          // VGMStream
EXTENSION(emff)         // VGMStream: Crystal Dynamics .MUL
EXTENSION(enm)          // VGMStream
EXTENSION(eno)          // VGMStream: Ogg Vorbis Encrypted
EXTENSION(ens)          // VGMStream: Z-Axis ZSND
EXTENSION(esf)          // VGMStream: Eurocom ESF
EXTENSION(exa)          // VGMStream: Electronic Arts SCHl
EXTENSION(ezw)          // VGMStream
EXTENSION(fag)          // VGMStream: Radical .FAG
EXTENSION(fcb)          // VGMStream: Bink Audio
EXTENSION(fda)          // VGMStream: Apple AIFF-C
EXTENSION(amx)          // VGMStream
EXTENSION(filp)         // VGMStream
EXTENSION(fish)         // VGMStream: Ogg Vorbis Encrypted
EXTENSION(flx)          // VGMStream: Ultima IX .FLX
EXTENSION(fsb)          // VGMStream: FMOD FSB
EXTENSION(fwav)         // VGMStream
EXTENSION(fwse)         // VGMStream
EXTENSION(g1l)          // VGMStream: Koei Tecmo WiiBGM
EXTENSION(gbts)         // VGMStream: Pop'n'Music 9
EXTENSION(gca)          // VGMStream: GCA DSP
EXTENSION(gcm)          // VGMStream: Double DSP
EXTENSION(gcub)         // VGMStream: Sega GCub
EXTENSION(gcw)          // VGMStream: MileStone GCSW
EXTENSION(genh)         // VGMStream: GENH Generic
EXTENSION(gin)          // VGMStream
EXTENSION(gms)          // VGMStream: Game Arts .SEB
EXTENSION(grn)          // VGMStream: Sony XA
EXTENSION(gsp)          // VGMStream: Tecmo GSND
EXTENSION(gtd)          // VGMStream: Hexadrive GHS/S_P_STH
EXTENSION(gwm)          // VGMStream
EXTENSION(h4m)          // VGMStream: Hudson HVQM4
EXTENSION(hab)          // VGMStream
EXTENSION(hca)          // VGMStream: CRI HCA
EXTENSION(hd3)          // VGMStream: Sony HD3+BD3
EXTENSION(hdr)          // VGMStream
EXTENSION(hdt)          // VGMStream
EXTENSION(his)          // VGMStream: Her Interactive HIS
EXTENSION(hps)          // VGMStream: HAL Laboratory HALPST
EXTENSION(hsf)          // VGMStream: Lowrider 'HSF'
EXTENSION(hvqm)         // VGMStream
EXTENSION(hwas)         // VGMStream: Vicarious Visions HWAS
EXTENSION(hwb)          // VGMStream
EXTENSION(hwd)          // VGMStream
EXTENSION(hx2)          // VGMStream: Ubisoft HXx
EXTENSION(hx3)          // VGMStream: Ubisoft HXx
EXTENSION(hxc)          // VGMStream: Ubisoft HXx
EXTENSION(hxd)          // VGMStream: Ubisoft HXx
EXTENSION(hxg)          // VGMStream: Ubisoft HXx
EXTENSION(hxx)          // VGMStream: Ubisoft HXx
EXTENSION(iab)          // VGMStream: Runtime .IAB
EXTENSION(iadp)         // VGMStream
EXTENSION(idmsf)        // VGMStream: id Software MZRT
EXTENSION(idsp)         // VGMStream: TOSE .IDSP
EXTENSION(idvi)         // VGMStream: Capcom IDVI
EXTENSION(idwav)        // VGMStream
EXTENSION(ifs)          // VGMStream: Konami BPM
EXTENSION(ikm)          // VGMStream: MiCROViSiON IKM
EXTENSION(ild)          // VGMStream: Tose ILD
EXTENSION(ima)          // VGMStream
EXTENSION(imc)          // VGMStream: LucasArts iMuse
EXTENSION(imx)          // VGMStream: LucasArts iMuse
EXTENSION(int)          // VGMStream: PS2 .int raw
EXTENSION(is14)         // VGMStream
EXTENSION(isb)          // VGMStream: Creative ISACT
EXTENSION(isd)          // VGMStream: Ogg Vorbis Encrypted
EXTENSION(isws)         // VGMStream: Sumo Digital iSWS
EXTENSION(itl)          // VGMStream: .ITL DSP
EXTENSION(ivag)         // VGMStream
EXTENSION(ivaud)        // VGMStream: Rockstar .ivaud
EXTENSION(ivb)          // VGMStream: IVB/BVII
EXTENSION(joe)          // VGMStream: Asobo Studio .JOE
EXTENSION(jstm)         // VGMStream: JSTM
EXTENSION(kat)          // VGMStream
EXTENSION(kces)         // VGMStream
EXTENSION(kcey)         // VGMStream: Konami KCEY
EXTENSION(km9)          // VGMStream: Koei Tecmo KMA9
EXTENSION(kmx)          // VGMStream: Microsoft XMA RIFF
EXTENSION(kno)          // VGMStream: Koei Tecmo KTSS
EXTENSION(kns)          // VGMStream: Koei Tecmo KTSS
EXTENSION(koe)          // VGMStream
EXTENSION(kovs)         // VGMStream: Ogg Vorbis KOVS
EXTENSION(kraw)         // VGMStream: Geometry Wars: Galaxies KRAW
EXTENSION(ktac)         // VGMStream: Koei Tecmo KTAC
EXTENSION(ktsl2asbin)   // VGMStream: RIFF WAVE (smpl looping)
EXTENSION(ktss)         // VGMStream: Koei Tecmo KTSS
EXTENSION(kvs)          // VGMStream: Ogg Vorbis KOVS
EXTENSION(kwa)          // VGMStream: Kuju London .KWA
EXTENSION(l)            // VGMStream: Sony VAG
EXTENSION(laac)         // VGMStream: AAC
EXTENSION(ladpcm)       // VGMStream: French-Bread LPCM
EXTENSION(laif)         // VGMStream: Apple AIFF-C
EXTENSION(laifc)        // VGMStream
EXTENSION(laiff)        // VGMStream
EXTENSION(lac3)         // VGMStream
EXTENSION(lasf)         // VGMStream: Electronic Arts SCHl
EXTENSION(lbin)         // VGMStream: Konami LP/AP/LEP
EXTENSION(ldat)         // VGMStream: RIFF WAVE
EXTENSION(ldt)          // VGMStream
EXTENSION(cat)          // VGMStream
EXTENSION(lep)          // VGMStream
EXTENSION(lflac)        // VGMStream: raw FLAC
EXTENSION(lin)          // VGMStream: Electronic Arts SCHl
EXTENSION(lm0)          // VGMStream
EXTENSION(lm1)          // VGMStream: Ubisoft SBx
EXTENSION(lm2)          // VGMStream
EXTENSION(lm3)          // VGMStream: Ubisoft SBx
EXTENSION(lm4)          // VGMStream
EXTENSION(lm5)          // VGMStream
EXTENSION(lm6)          // VGMStream
EXTENSION(lm7)          // VGMStream
EXTENSION(lmp2)         // VGMStream: MPEG
EXTENSION(lmp3)         // VGMStream: MPEG
EXTENSION(lmp4)         // VGMStream: MP4/AAC
EXTENSION(lmpc)         // VGMStream
EXTENSION(logg)         // VGMStream: Audiokinetic Wwise RIFF Custom Vorbis
EXTENSION(lopus)        // VGMStream: Nintendo Switch OPUS
EXTENSION(lp)           // VGMStream
EXTENSION(lpcm)         // VGMStream: Shade LPCM
EXTENSION(lpk)          // VGMStream: Ubisoft BAO
EXTENSION(lps)          // VGMStream: Rave Master LPS
EXTENSION(lrmh)         // VGMStream: Sony LRMD
EXTENSION(lse)          // VGMStream: Ogg Vorbis Encrypted
EXTENSION(lsf)          // VGMStream: Gizmondo Studios Helsingborg LSF
EXTENSION(lstm)         // VGMStream: Angel Studios/Rockstar San Diego STMA
EXTENSION(lwav)         // VGMStream: RIFF Wave (XBOX)
EXTENSION(lwd)          // VGMStream
EXTENSION(lwma)         // VGMStream: FFmpeg
EXTENSION(m4a)          // VGMStream: MP4/AAC
EXTENSION(m4v)          // VGMStream
EXTENSION(mab)          // VGMStream: Square Enix MAB
EXTENSION(map)          // VGMStream: Electronic Arts SCHl
EXTENSION(mc3)          // VGMStream: Paradigm MC3
EXTENSION(mca)          // VGMStream
EXTENSION(mcadpcm)      // VGMStream
EXTENSION(mcg)          // VGMStream
EXTENSION(mds)          // VGMStream
EXTENSION(mdsp)         // VGMStream
EXTENSION(mi4)          // VGMStream
EXTENSION(mib)          // VGMStream: Headerless PS-ADPCM raw
EXTENSION(mic)          // VGMStream: KOEI .MIC
EXTENSION(msx)          // VGMStream
EXTENSION(mjb)          // VGMStream
EXTENSION(mnstr)        // VGMStream
EXTENSION(mogg)         // VGMStream
EXTENSION(mov)          // VGMStream
EXTENSION(mp2)          // MP3 & VGMStream
EXTENSION(mp4)          // VGMStream: MP4/AAC
EXTENSION(mpc)          // VGMStream: Musepack SV8
EXTENSION(mpds)         // VGMStream
EXTENSION(mpdsp)        // VGMStream
EXTENSION(mpf)          // VGMStream: Electronic Arts SCHl
EXTENSION(ms)           // VGMStream
EXTENSION(msa)          // VGMStream
EXTENSION(msb)          // VGMStream
EXTENSION(msd)          // VGMStream
EXTENSION(mse)          // VGMStream
EXTENSION(msf)          // VGMStream: Sony MSF
EXTENSION(mss)          // VGMStream
EXTENSION(msv)          // VGMStream
EXTENSION(msvp)         // VGMStream
EXTENSION(mta2)         // VGMStream
EXTENSION(mtaf)         // VGMStream: Konami MTAF
EXTENSION(mul)          // VGMStream: Crystal Dynamics .MUL
EXTENSION(mups)         // VGMStream
EXTENSION(musc)         // VGMStream: Krome MUSC
EXTENSION(musx)         // VGMStream: Eurocom MUSX
EXTENSION(mwv)          // VGMStream: RIFF Wave (Level 5)
EXTENSION(mxst)         // VGMStream
EXTENSION(myspd)        // VGMStream
EXTENSION(n64)          // VGMStream
EXTENSION(naac)         // VGMStream
EXTENSION(nds)          // VGMStream
EXTENSION(ndp)          // VGMStream
EXTENSION(nlsd)         // VGMStream
EXTENSION(nop)          // VGMStream
EXTENSION(nps)          // VGMStream
EXTENSION(npsf)         // VGMStream: Namco NPSF
EXTENSION(nsa)          // VGMStream
EXTENSION(nsopus)       // VGMStream
EXTENSION(nub)          // VGMStream
EXTENSION(nub2)         // VGMStream
EXTENSION(nus3audio)    // VGMStream
EXTENSION(nus3bank)     // VGMStream
EXTENSION(nwa)          // VGMStream: VisualArt's NWA
EXTENSION(nxa)          // VGMStream
EXTENSION(nxopus)       // VGMStream
EXTENSION(ogg_)         // VGMStream
EXTENSION(ogl)          // VGMStream
EXTENSION(ogv)          // VGMStream
EXTENSION(oma)          // VGMStream: Sony OpenMG audio
EXTENSION(omu)          // VGMStream
EXTENSION(opu)          // VGMStream
EXTENSION(opusx)        // VGMStream: Nintendo Switch OPUS
EXTENSION(otm)          // VGMStream
EXTENSION(p2bt)         // VGMStream
EXTENSION(p3d)          // VGMStream
EXTENSION(past)         // VGMStream
EXTENSION(pcm)          // VGMStream: Konami .PCM
EXTENSION(pk)           // VGMStream: Ubisoft BAO
EXTENSION(pona)         // VGMStream
EXTENSION(pos)          // VGMStream: loop assist
EXTENSION(ps3)          // VGMStream
EXTENSION(ps3audio)     // VGMStream: FFmpeg
EXTENSION(psb)          // VGMStream: M2 PSB
EXTENSION(psh)          // VGMStream
EXTENSION(psn)          // VGMStream
EXTENSION(pwb)          // VGMStream
EXTENSION(r)            // VGMStream: Sony VAG
EXTENSION(rak)          // VGMStream
EXTENSION(ras)          // VGMStream
EXTENSION(rda)          // VGMStream
EXTENSION(rkv)          // VGMStream
EXTENSION(rnd)          // VGMStream
EXTENSION(rof)          // VGMStream
EXTENSION(rpgmvo)       // VGMStream: Ogg Vorbis Encrypted
EXTENSION(rrds)         // VGMStream
EXTENSION(rsd)          // VGMStream: Radical RSD
EXTENSION(rsf)          // VGMStream
EXTENSION(rsm)          // VGMStream
EXTENSION(rsp)          // VGMStream
EXTENSION(rstm)         // VGMStream: Rockstar Games RSTM
EXTENSION(rvws)         // VGMStream
EXTENSION(rwar)         // VGMStream
EXTENSION(rwav)         // VGMStream: Nintendo RWAV
EXTENSION(rws)          // VGMStream: RenderWare RWS
EXTENSION(rwx)          // VGMStream
EXTENSION(s14)          // VGMStream
EXTENSION(s3v)          // VGMStream
EXTENSION(sab)          // VGMStream: Square Enix SAB
EXTENSION(sad)          // VGMStream
EXTENSION(saf)          // VGMStream
EXTENSION(sag)          // VGMStream
EXTENSION(sb0)          // VGMStream
EXTENSION(sb1)          // VGMStream
EXTENSION(sb2)          // VGMStream
EXTENSION(sb3)          // VGMStream
EXTENSION(sb4)          // VGMStream
EXTENSION(sb5)          // VGMStream
EXTENSION(sb6)          // VGMStream
EXTENSION(sb7)          // VGMStream
EXTENSION(sbk)          // VGMStream
EXTENSION(sbin)         // VGMStream
EXTENSION(sbr)          // VGMStream: Electronic Arts SPS
EXTENSION(sbv)          // VGMStream
EXTENSION(scd)          // VGMStream: Square Enix SCD
EXTENSION(sd9)          // VGMStream
EXTENSION(sdf)          // VGMStream
EXTENSION(sdt)          // VGMStream
EXTENSION(seb)          // VGMStream
EXTENSION(sed)          // VGMStream
EXTENSION(seg)          // VGMStream
EXTENSION(sf0)          // VGMStream
EXTENSION(sfl)          // VGMStream
EXTENSION(sfs)          // VGMStream
EXTENSION(sgb)          // VGMStream: Sony SGXD
EXTENSION(sgd)          // VGMStream
EXTENSION(sig)          // VGMStream
EXTENSION(sli)          // VGMStream: Ogg Vorbis (loop)
EXTENSION(sm0)          // VGMStream
EXTENSION(sm1)          // VGMStream: Ubisoft SBx
EXTENSION(sm4)          // VGMStream
EXTENSION(sm5)          // VGMStream
EXTENSION(sm6)          // VGMStream
EXTENSION(sm7)          // VGMStream
EXTENSION(smc)          // VGMStream
EXTENSION(smk)          // VGMStream: RAD Game Tools SMACKER
EXTENSION(smp)          // VGMStream: Infernal Engine .smp
EXTENSION(smv)          // VGMStream
EXTENSION(snb)          // VGMStream
EXTENSION(snd)          // VGMStream
EXTENSION(snds)         // VGMStream
EXTENSION(sngw)         // VGMStream
EXTENSION(snr)          // VGMStream: Electronic Arts SNR+SNS
EXTENSION(sns)          // VGMStream
EXTENSION(snu)          // VGMStream
EXTENSION(sod)          // VGMStream
EXTENSION(son)          // VGMStream
EXTENSION(spd)          // VGMStream
EXTENSION(spm)          // VGMStream
EXTENSION(sps)          // VGMStream: Electronic Arts SPS
EXTENSION(spsd)         // VGMStream: Sega Naomi SPSD
EXTENSION(spw)          // VGMStream
EXTENSION(srsa)         // VGMStream
EXTENSION(ss2)          // VGMStream: Sony ADS
EXTENSION(ssm)          // VGMStream
EXTENSION(ssp)          // VGMStream
EXTENSION(sspr)         // VGMStream
EXTENSION(sss)          // VGMStream
EXTENSION(ster)         // VGMStream
EXTENSION(sth)          // VGMStream
EXTENSION(stream)       // VGMStream
EXTENSION(strm)         // VGMStream: Nintendo STRM
EXTENSION(sts)          // VGMStream: Sony EXST
EXTENSION(sts_cp3)      // VGMStream
EXTENSION(svag)         // VGMStream: Konami SVAG
EXTENSION(svg)          // VGMStream
EXTENSION(svs)          // VGMStream
EXTENSION(swag)         // VGMStream
EXTENSION(swav)         // VGMStream: Nintendo SWAV
EXTENSION(swd)          // VGMStream
EXTENSION(swith_audio)  // VGMStream
EXTENSION(sx)           // VGMStream
EXTENSION(sxd)          // VGMStream
EXTENSION(sxd2)         // VGMStream
EXTENSION(sxd3)         // VGMStream
EXTENSION(szd)          // VGMStream
EXTENSION(szd1)         // VGMStream
EXTENSION(szd3)         // VGMStream
EXTENSION(tad)          // VGMStream
EXTENSION(tak)          // VGMStream: Tom's lossless Audio Kompressor
EXTENSION(tgq)          // VGMStream
EXTENSION(tgv)          // VGMStream
EXTENSION(thp)          // VGMStream: Nintendo THP
EXTENSION(tmx)          // VGMStream
EXTENSION(tra)          // VGMStream
EXTENSION(trk)          // VGMStream: Nintendo .DTK raw
EXTENSION(tun)          // VGMStream
EXTENSION(txth)         // VGMStream: TXTH generic (txth)
EXTENSION(txtp)         // VGMStream: TXTP generic
EXTENSION(u0)           // VGMStream
EXTENSION(ue4opus)      // VGMStream
EXTENSION(um3)          // VGMStream
EXTENSION(utk)          // VGMStream
EXTENSION(uv)           // VGMStream
EXTENSION(v0)           // VGMStream
EXTENSION(va3)          // VGMStream
EXTENSION(vab)          // VGMStream
EXTENSION(vag)          // VGMStream: Sony VAG
EXTENSION(vai)          // VGMStream
EXTENSION(vas)          // VGMStream: Konami VAS
EXTENSION(vbk)          // VGMStream
EXTENSION(vds)          // VGMStream
EXTENSION(vdm)          // VGMStream
EXTENSION(vgmstream)    // VGMStream
EXTENSION(vgs)          // VGMStream: Guitar Hero VGS
EXTENSION(vgv)          // VGMStream
EXTENSION(vh)           // VGMStream
EXTENSION(vid)          // VGMStream
EXTENSION(vig)          // VGMStream
EXTENSION(vis)          // VGMStream
EXTENSION(vms)          // VGMStream
EXTENSION(voi)          // VGMStream
EXTENSION(vp6)          // VGMStream
EXTENSION(vpk)          // VGMStream: SCE America VPK
EXTENSION(vs)           // VGMStream
EXTENSION(vsf)          // VGMStream
EXTENSION(vsv)          // VGMStream
EXTENSION(vxn)          // VGMStream: Gameloft VXN
EXTENSION(w)            // VGMStream
EXTENSION(waa)          // VGMStream: Ubisoft Jade RIFF
EXTENSION(wac)          // VGMStream: Ubisoft Jade RIFF
EXTENSION(wad)          // VGMStream
EXTENSION(waf)          // VGMStream
EXTENSION(wam)          // VGMStream: Ubisoft Jade RIFF
EXTENSION(was)          // VGMStream
EXTENSION(wavc)         // VGMStream
EXTENSION(wave)         // VGMStream: EngineBlack .WAVE
EXTENSION(wavebatch)    // VGMStream
EXTENSION(way)          // VGMStream
EXTENSION(wb2)          // VGMStream
EXTENSION(wbd)          // VGMStream
EXTENSION(wbk)          // VGMStream
EXTENSION(wd)           // VGMStream
EXTENSION(wem)          // VGMStream: Audiokinetic Wwise RIFF
EXTENSION(nfx)          // VGMStream
EXTENSION(wma)          // VGMStream: FFmpeg
EXTENSION(wmus)         // VGMStream
EXTENSION(wp2)          // VGMStream
EXTENSION(wpd)          // VGMStream
EXTENSION(wsd)          // VGMStream
EXTENSION(wsi)          // VGMStream
EXTENSION(wua)          // VGMStream
EXTENSION(wv2)          // VGMStream
EXTENSION(wv6)          // VGMStream
EXTENSION(wve)          // VGMStream
EXTENSION(wvs)          // VGMStream
EXTENSION(wvx)          // VGMStream
EXTENSION(wxd)          // VGMStream
EXTENSION(x)            // VGMStream
EXTENSION(x360audio)    // VGMStream
EXTENSION(xa)           // VGMStream: Sony XA
EXTENSION(xa2)          // VGMStream
EXTENSION(xa30)         // VGMStream
EXTENSION(xai)          // VGMStream
EXTENSION(xau)          // VGMStream
EXTENSION(xav)          // VGMStream
EXTENSION(xen)          // VGMStream
EXTENSION(xma)          // VGMStream: Microsoft XMA RIFF
EXTENSION(xma2)         // VGMStream
EXTENSION(xmd)          // VGMStream
EXTENSION(xms)          // Adlib: XMS-Tracker & VGMStream
EXTENSION(xmu)          // VGMStream
EXTENSION(xmv)          // VGMStream
EXTENSION(xnb)          // VGMStream: Microsoft XNA Game Studio
EXTENSION(xopus)        // VGMStream
EXTENSION(xps)          // VGMStream
EXTENSION(xse)          // VGMStream
EXTENSION(xsew)         // VGMStream
EXTENSION(xsf)          // VGMStream
EXTENSION(xsh)          // VGMStream
EXTENSION(xss)          // VGMStream
EXTENSION(xvag)         // VGMStream: Sony XVAG
EXTENSION(v)			// VGMStream
EXTENSION(xwav)         // VGMStream: RIFF Wave (XBOX)
EXTENSION(xwb)          // VGMStream: Microsoft XWB
EXTENSION(xwc)          // VGMStream
EXTENSION(xwm)          // VGMStream
EXTENSION(xwma)         // VGMStream: Microsoft XWMA RIFF
EXTENSION(xws)          // VGMStream
EXTENSION(xwv)          // VGMStream
EXTENSION(ydsp)         // VGMStream
EXTENSION(ymf)          // VGMStream
EXTENSION(zic)          // VGMStream
EXTENSION(zsd)          // VGMStream: Z-Axis ZSND
EXTENSION(zss)          // VGMStream
EXTENSION(zwdsp)        // VGMStream
EXTENSION(zwv)          // VGMStream
EXTENSION(wsr)          // WonderSwan
EXTENSION(org)          // Organya
EXTENSION(kdm)          // Ken
EXTENSION(amad)         // Ayumi
EXTENSION(fxm)          // Ayumi
EXTENSION(dnm)          // Furnace: Dn-FamiTracker
EXTENSION(0cc)          // Furnace: 0CC-FamiTracker
EXTENSION(eft)          // Furnace: E-FamiTracker
EXTENSION(cbx)          // VGMStream
EXTENSION(ged)          // VGMStream
EXTENSION(gwb)          // VGMStream
EXTENSION(move)         // VGMStream
EXTENSION(no)           // VGMStream
EXTENSION(wax)          // VGMStream
EXTENSION(se)           // VGMStream
EXTENSION(unic)         // OpenMPT: UNIC Tracker
EXTENSION(apm)          // VGMStream
EXTENSION(sdd)          // VGMStream
EXTENSION(sd1)          // VGMStream
EXTENSION(plx)          // Adlib: PALLADIX Sound System
EXTENSION(psy)          // Psycle