//just add at the end of the list new extensions
EXTENSION(mptm)
EXTENSION(mod)
EXTENSION(s3m)
EXTENSION(xm)
EXTENSION(it)
EXTENSION(669)
EXTENSION(amf)
EXTENSION(ams)
EXTENSION(c67)
EXTENSION(dbm)
EXTENSION(digi)
EXTENSION(dmf)
EXTENSION(dsm)
EXTENSION(dtm)
EXTENSION(far)
EXTENSION(imf)
EXTENSION(ice)
EXTENSION(j2b)
EXTENSION(m15)
EXTENSION(mdl)
EXTENSION(med)      // OpenMPT & UADE: Octa-MED
EXTENSION(mms)      // OpenMPT & UADE: MultiMedia_Sound
EXTENSION(mt2)
EXTENSION(mtm)
EXTENSION(nst)
EXTENSION(okt)      // OpenMPT & UADE: Oktalyzer
EXTENSION(plm)
EXTENSION(psm)      // ZXTune: Pro Sound Maker
EXTENSION(pt36)
EXTENSION(ptm)
EXTENSION(sfx)      // OpenMPT & UADE: Sound-FX
EXTENSION(sfx2)
EXTENSION(st26)
EXTENSION(stk)
EXTENSION(stm)
EXTENSION(stp)      // ZXTune: Sound Tracker Pro
EXTENSION(ult)
EXTENSION(wow)
EXTENSION(gdm)
EXTENSION(mo3)
EXTENSION(oxm)
EXTENSION(umx)
EXTENSION(xpk)
EXTENSION(ppm)
EXTENSION(mmcmp)
EXTENSION(hvl)
EXTENSION(ahx)
EXTENSION(bp)       // SoundMon & UAE: SoundMon2.0
EXTENSION(ym)       // ZXTune: ST-Sound
EXTENSION(dsym)
EXTENSION(fmt)
EXTENSION(mus)      // OpenMPT: ? & Sidplay: ? & UADE: UFO & NEZplug: FAC SoundTracker
EXTENSION(stx)
EXTENSION(symmod)
EXTENSION(smod)
EXTENSION(fc)
EXTENSION(rsid)
EXTENSION(psid)
EXTENSION(v2m)
EXTENSION(sndh)
EXTENSION(sc68)
EXTENSION(hsc)
EXTENSION(sng)      // Adlib: ? : UADE: ZoundMonitor
EXTENSION(wlf)
EXTENSION(adlib)
EXTENSION(a2m)
EXTENSION(amd)
EXTENSION(bam)
EXTENSION(cmf)
EXTENSION(d00)
EXTENSION(dfm)
EXTENSION(hsp)
EXTENSION(ksm)
EXTENSION(mad)
EXTENSION(ims)      // Adlib: Midi/IMS & UADE: ImagesMusicSystem
EXTENSION(mdi)
EXTENSION(mid)
EXTENSION(sci)
EXTENSION(laa)
EXTENSION(mkj)
EXTENSION(cff)
EXTENSION(dmo)
EXTENSION(mtk)
EXTENSION(rad)
EXTENSION(rac)
EXTENSION(raw)
EXTENSION(sat)
EXTENSION(sa2)
EXTENSION(xad)
EXTENSION(bmf)
EXTENSION(lds)
EXTENSION(m)
EXTENSION(rol)
EXTENSION(xsm)
EXTENSION(dro)
EXTENSION(msc)
EXTENSION(rix)
EXTENSION(adl)
EXTENSION(jbm)
EXTENSION(got)
EXTENSION(vgm)
EXTENSION(vgz)
EXTENSION(sop)
EXTENSION(hsq)
EXTENSION(sqx)
EXTENSION(sdb)
EXTENSION(agd)
EXTENSION(ha2)
EXTENSION(bp3)      // SoundMon & UAE: SoundMon2.2
EXTENSION(sap)
EXTENSION(cmc)
EXTENSION(cm3)
EXTENSION(cmr)
EXTENSION(cms)
EXTENSION(dmc)
EXTENSION(dlt)
EXTENSION(mpt)
EXTENSION(mpd)
EXTENSION(rmt)
EXTENSION(tmc)
EXTENSION(tm8)
EXTENSION(tm2)
EXTENSION(tfm)
EXTENSION(mp3)
EXTENSION(flac)
EXTENSION(ogg)
EXTENSION(ay)       // Ayfly & GME & NEZplug & ZXTune: AY/Emul
EXTENSION(vtx)      // ZXTune: Vortex Project
EXTENSION(psg)      // ZXTune: Programmable Sound Generator
EXTENSION(asc)      // ZXTune: ASC Sound Master
EXTENSION(pt1)      // ZXTune: Pro Tracker
EXTENSION(pt2)      // ZXTune: Pro Tracker
EXTENSION(pt3)      // ZXTune: Pro Tracker
EXTENSION(stc)      // ZXTune: Sound Tracker
EXTENSION(sqt)      // AyFly: ? & UADE: Quartet_PSG & ZXTune: SQ-Tracker
EXTENSION(psc)      // ZXTune: Pro Sound Creator
EXTENSION(gbs)      // GBSPlay & GME & NEZplug
EXTENSION(gbr)      // GBSPlay & NEZplug
EXTENSION(gb)
EXTENSION(gym)
EXTENSION(hes)      // GME & NEZplug
EXTENSION(kss)      // KSS & GME & NEZplug
EXTENSION(nsf)      // GME & NEZplug
EXTENSION(nsfe)     // GME & NEZplug
EXTENSION(spc)
EXTENSION(rsn)
EXTENSION(mdx)
EXTENSION(mdxPk)
EXTENSION(s98)
EXTENSION(aps)      // UADE: AProSys
EXTENSION(ast)      // UADE: ActionAmics
EXTENSION(adpcm)    // UADE: ADPCM_mono
EXTENSION(amc)      // UADE: AM-Composer
EXTENSION(abk)      // UADE: AMOS
EXTENSION(hot)      // UADE: Anders_0land
EXTENSION(aam)      // UADE: ArtAndMagic
EXTENSION(alp)      // UADE: Alcatraz_Packer
EXTENSION(bye)      // UADE: Andrew_Parton
EXTENSION(aon)      // UADE: ArtOfNoise
EXTENSION(ash)      // UADE: Ashley_Hogg
EXTENSION(adsc)     // UADE: AudioSculpture
EXTENSION(bss)      // UADE: BeathovenSynthesizer
EXTENSION(bd)       // UADE: BenDaglish
EXTENSION(bds)      // UADE: BenDaglish-SID
EXTENSION(uds)      // UADE: BladePacker
EXTENSION(kris)     // UADE: ChipTracker
EXTENSION(cin)      // UADE: Cinemaware
EXTENSION(core)     // UADE: CoreDesign
EXTENSION(cus)      // UADE: custom
EXTENSION(cm)       // UADE: CustomMade
EXTENSION(dz)       // UADE: DariusZendeh
EXTENSION(dl)       // UADE: DaveLowe
EXTENSION(dl_deli)  // UADE: DaveLowe_Deli
EXTENSION(dln)      // UADE: DaveLoweNew
EXTENSION(dh)       // UADE: DavidHanney
EXTENSION(dw)       // UADE: DavidWhittaker
EXTENSION(dm)       // UADE: DeltaMusic1.3
EXTENSION(dm2)      // UADE: DeltaMusic2.0
EXTENSION(dsr)      // UADE: Desire
EXTENSION(dsc)      // UADE: DigitalSonixChrome
EXTENSION(dss)      // UADE: DigitalSoundStudio
EXTENSION(dns)      // UADE: DynamicSynthesizer
EXTENSION(ems)      // UADE: EMS & EMS-6
EXTENSION(ex)       // UADE: FashionTracker
EXTENSION(fred)     // UADE: Fred
EXTENSION(gray)     // UADE: FredGray
EXTENSION(bsi)      // UADE: FutureComposer-BSI
EXTENSION(fp)       // UADE: FuturePlayer
EXTENSION(fw)       // UADE: ForgottenWorlds_Game
EXTENSION(glue)     // UADE: GlueMon
EXTENSION(gmc)      // UADE: GMC
EXTENSION(ea)       // UADE: EarAche
EXTENSION(hd)       // UADE: HowieDavies
EXTENSION(hipc)     // UADE: JochenHippel-CoSo
EXTENSION(emod)     // UADE: QuadraComposer
EXTENSION(dum)      // UADE: Infogrames
EXTENSION(is)       // UADE: InStereo
EXTENSION(is20)     // UADE: InStereo2.0
EXTENSION(jam)      // UADE: JamCracker
EXTENSION(jmf)      // UADE: JankoMrsicFlogel
EXTENSION(js)       // UADE: Janne_Salmijarvi_Optimizer
EXTENSION(jb)       // UADE: JasonBrooke
EXTENSION(jpn)      // UADE: JasonPage
EXTENSION(jpo)      // UADE: JasonPage_JP & UADE: SteveTurner
EXTENSION(jt)       // UADE: JeroenTel
EXTENSION(jo)       // UADE: JesperOlsen
EXTENSION(hip)      // UADE: JochenHippel
EXTENSION(hip7)     // UADE: JochenHippel-7V
EXTENSION(hst)      // UADE: Jochen_Hippel_ST
EXTENSION(kim)      // UADE: Kim_Christensen
EXTENSION(kh)       // UADE: KrisHatlelid
EXTENSION(pt)       // UADE: Laxity
EXTENSION(lme)      // UADE: LegglessMusicEditor
EXTENSION(mon)      // UADE: ManiacsOfNoise
EXTENSION(mfp)      // UADE: MagneticFieldsPacker
EXTENSION(hn)       // UADE: MajorTom
EXTENSION(mc)       // UADE: Mark_Cooksey
EXTENSION(mco)      // UADE: Mark_Cooksey_Old
EXTENSION(mk2)      // UADE: MarkII
EXTENSION(avp)      // UADE: MartinWalker
EXTENSION(max)      // UADE: Maximum_Effect
EXTENSION(midi)     // UADE: MIDI-Loriciel
EXTENSION(md)       // UADE: MikeDavies
EXTENSION(mosh)     // UADE: Mosh_Packer
EXTENSION(mmdc)     // UADE: MMDC
EXTENSION(dmu)      // UADE: Mugician
EXTENSION(dmu2)     // UADE: MugicianII
EXTENSION(ma)       // UADE: MusicAssembler
EXTENSION(mm4)      // UADE: MusicMaker-4V
EXTENSION(mm8)      // UADE: MusicMaker-8V
EXTENSION(npp)      // UADE: Nick_Pelling_Packer
EXTENSION(ntp)      // UADE: NovoTradePacker
EXTENSION(two)      // UADE: NTSP-system
EXTENSION(one)      // UADE: onEscapee
EXTENSION(dat)      // UADE: PaulRobotham
EXTENSION(ps)       // UADE: PaulShields
EXTENSION(snk)      // UADE: PaulSummers
EXTENSION(pat)      // UADE: Paul_Tonge
EXTENSION(pvp)      // UADE: PeterVerswyvelen
EXTENSION(pap)      // UADE: PierreAdane
EXTENSION(pn)       // UADE: Pokeynoise
EXTENSION(psa)      // UADE: ProfessionalSoundArtists
EXTENSION(puma)     // UADE: PumaTracker
EXTENSION(rj)       // UADE: RichardJoseph
EXTENSION(rjp)      // UADE: RichardJoseph_Player
EXTENSION(riff)     // UADE: RiffRaff
EXTENSION(rh)       // UADE: RobHubbard
EXTENSION(rho)      // UADE: RobHubbard_ST
EXTENSION(scumm)    // UADE: SCUMM
EXTENSION(scn)      // UADE: SeanConnolly
EXTENSION(scr)      // UADE: SeanConran
EXTENSION(sid1)     // UADE: SIDMon1.0
EXTENSION(sid2)     // UADE: SIDMon2.0
EXTENSION(mok)      // UADE: Silmarils
EXTENSION(sa)       // UADE: SonicArranger
EXTENSION(smus)     // UADE: SonixMusicDriver
EXTENSION(spl)      // UADE: SoundProgrammingLanguage
EXTENSION(sc)       // UADE: SoundControl
EXTENSION(psf)      // UADE: SoundFactory & Highly Experimental
EXTENSION(tw)       // UADE: SoundImages
EXTENSION(sm)       // UADE: SoundMaster
EXTENSION(sm2)      // UADE: SoundMaster
EXTENSION(sm3)      // UADE: SoundMaster
EXTENSION(smpro)    // UADE: SoundMaster
EXTENSION(sjs)      // UADE: SoundPlayer
EXTENSION(jd)       // UADE: Special-FX
EXTENSION(doda)     // UADE: Special-FX_ST
EXTENSION(sas)      // UADE: SpeedyA1System
EXTENSION(ss)       // UADE: SpeedySystem
EXTENSION(sb)       // UADE: SteveBarrett
EXTENSION(sun)      // UADE: SUN-Tronic
EXTENSION(syn)      // UADE: Synth
EXTENSION(sdr)      // UADE: SynthDream
EXTENSION(osp)      // UADE: SynthPack
EXTENSION(synmod)   // UADE: SynTracker
EXTENSION(tcb)      // UADE: TCB_Tracker
EXTENSION(mdst)     // UADE: TFMX_ST
EXTENSION(thm)      // UADE: ThomasHermann
EXTENSION(tmk)      // UADE: TimeTracker
EXTENSION(tits)     // UADE: Titanics_Packer
EXTENSION(tme)      // UADE: TheMusicalEnlightenment
EXTENSION(sg)       // UADE: TomyTracker
EXTENSION(dp)       // UADE: Tronic
EXTENSION(vss)      // UADE: VoodooSupremeSynthesizer
EXTENSION(wb)       // UADE: WallyBeben
EXTENSION(ml)       // UADE: MusiclineEditor
EXTENSION(agi)      // UADE: Sierra-AGI
EXTENSION(tpu)      // UADE: DirkBialluch
EXTENSION(qpa)      // UADE: Quartet
EXTENSION(qts)      // UADE: Quartet_ST & Quartet
EXTENSION(miniqsf)  // Highly Quixotic
EXTENSION(qsfPk)    // Highly Quixotic
EXTENSION(minigsf)  // Highly Advanced
EXTENSION(gsfPk)    // Highly Advanced
EXTENSION(ymst)     // UADE: YMST
EXTENSION(wav)      // WAV
EXTENSION(sid)      // SidPlay & UADE: SidMon1
EXTENSION(mug)      // UADE: Mugician
EXTENSION(mso)      // UADE: Medley
EXTENSION(ptk)      // ProTrekkr
EXTENSION(mdy)      // Adlib: AdLib MIDI/IMS Format
EXTENSION(mcr)      // UADE: Mark_Cooksey_Old
EXTENSION(mgb)      // Gameboy Tracker: no known replay :(
EXTENSION(ixs)      // iXalance
EXTENSION(mgs)      // KSS
EXTENSION(bgm)      // KSS
EXTENSION(opx)      // KSS
EXTENSION(mpk)      // KSS
EXTENSION(mbm)      // KSS
EXTENSION(sgc)      // NEZplug
EXTENSION(nsd)      // NEZplug
EXTENSION(pis)      // AdLib: Beni Tracker
EXTENSION(667)      // OpenMPT: Composer 667
EXTENSION(gtk)      // OpenMPT: Gramouf Tracker
EXTENSION(gt2)      // OpenMPT: Gramouf Tracker
EXTENSION(xmf)      // OpenMPT
EXTENSION(mdat)     // TFMX & UADE: TFMX
EXTENSION(ttt)      // TIATracker
EXTENSION(mini2sf)  // vio2sf
EXTENSION(2sfPk)    // vio2sf
EXTENSION(minissf)  // Highly Theoretical
EXTENSION(ssfPk)    // Highly Theoretical
EXTENSION(minidsf)  // Highly Theoretical
EXTENSION(dsfPk)    // Highly Theoretical
EXTENSION(ssf)      // Highly Theoretical
EXTENSION(dsf)      // Highly Theoretical
EXTENSION(gsf)      // Highly Advanced
EXTENSION(2sf)      // vio2sf
EXTENSION(minipsf)  // Highly Experimental
EXTENSION(psfPk)    // Highly Experimental
EXTENSION(psf2)     // Highly Experimental
EXTENSION(minipsf2) // Highly Experimental
EXTENSION(psf2Pk)   // Highly Experimental
EXTENSION(usf)      // LazyUSF
EXTENSION(miniusf)  // LazyUSF
EXTENSION(usfPk)    // LazyUSF
EXTENSION(tf)       // UADE: TimFollin
EXTENSION(cust)     // UADE: custom
EXTENSION(snsf)     // Highly Competitive
EXTENSION(minisnsf) // Highly Competitive
EXTENSION(snsfPk)   // Highly Competitive
EXTENSION(prt)      // UADE: PreTracker
EXTENSION(mtr)      // Adlib: Master Tracker
EXTENSION(buz2)     // Buzzic 2
EXTENSION(txt)      // ZXTune: VortexTracker
EXTENSION(st1)      // ZXTune: Sound Tracker
EXTENSION(st3)      // ZXTune: Sound Tracker
EXTENSION(ts)       // ZXTune: TurboSound
EXTENSION(gtr)      // ZXTune: Global Tracker
EXTENSION(ayc)      // ZXTune: CPC AYC
EXTENSION(ftc)      // ZXTune: Fast Tracker
EXTENSION(as0)      // ZXTune: ASC Sound Master
EXTENSION(str)      // ZXTune: Sample Tracker
EXTENSION(chi)      // ZXTune: Chip Tracker
EXTENSION(sqd)      // ZXTune: SQ Digital Tracker
EXTENSION(dmm)      // ZXTune: Digital Music Maker
EXTENSION(pdt)      // ZXTune: ProDigi Tracker
EXTENSION(dst)      // ZXTune: Digital Studio
EXTENSION(et1)      // ZXTune: Extreme Tracker
EXTENSION(mtc)      // ZXTune: Multitrack Container
EXTENSION(cop)      // ZXTune: E-Tracker
EXTENSION(tfe)      // ZXTune: TFM Music Maker
EXTENSION(tf0)      // ZXTune: TFM Music Maker
EXTENSION(tfd)      // ZXTune: TurboFM
EXTENSION(tfc)      // ZXTune: TurboFM
EXTENSION(trd)      // ZXTune: TR-DOS
EXTENSION(szx)      // ZXTune: ZXState
EXTENSION(scl)      // ZXTune: SINCLAIR
EXTENSION(hrp)      // ZXTune: Hrust RiP
EXTENSION(zip)      // ZXTune: ZXZip
EXTENSION(bin)      // ZXTune: Hrust v1
EXTENSION(p)        // ZXTune: Hrust v2
EXTENSION(fdi)      // ZXTune: Full Disk Image
EXTENSION(hbt)      // ZXTune: Hobeta
EXTENSION(hrm)      // ZXTune: Hrum
EXTENSION(dsq)      // ZXTune: DataSqueezer
EXTENSION(esv)      // ZXTune: ESVCruncher
EXTENSION(tlz)      // ZXTune: TurboLZ
EXTENSION(tlzp)     // ZXTune: TurboLZ
EXTENSION(trs)      // ZXTune: Trush
EXTENSION(cc3)      // ZXTune: CodeCruncher
EXTENSION(gam)      // ZXTune: GamePacker
EXTENSION(gamplus)  // ZXTune: GamePacker
EXTENSION(lzs)      // ZXTune: ASCLZSPack
EXTENSION(msp)      // ZXTune: MicrospacePacker
EXTENSION(td0)      // ZXTune: TeleDisk Image
EXTENSION(pcd)      // ZXTune: Powerfull Code Decreaser
EXTENSION(soc)      // UADE: Jochen_Hippel_ST
EXTENSION(sog)      // UADE: Jochen_Hippel_ST
EXTENSION(mcmd)     // UADE: JochenHippel
EXTENSION(mbmPk)    // KSS
EXTENSION(musPk)    // NEZplug: FAC SoundTracker
EXTENSION(eup)      // Euphony
EXTENSION(eupPk)    // Euphony
EXTENSION(4v)       // Quartet
EXTENSION(fur)      // Furnace
EXTENSION(aac)      // AAC