//just add at the end of the list new extensions
EXTENSION(mptm)
EXTENSION(mod)
EXTENSION(s3m)
EXTENSION(xm)
EXTENSION(it)
EXTENSION(669)
EXTENSION(amf)
EXTENSION(ams)
EXTENSION(c67)
EXTENSION(dbm)
EXTENSION(digi)
EXTENSION(dmf)
EXTENSION(dsm)
EXTENSION(dtm)
EXTENSION(far)
EXTENSION(imf)
EXTENSION(ice)
EXTENSION(j2b)
EXTENSION(m15)
EXTENSION(mdl)
EXTENSION(med)      // OpenMPT & UADE: Octa-MED
EXTENSION(mms)      // OpenMPT & UADE: MultiMedia_Sound
EXTENSION(mt2)
EXTENSION(mtm)
EXTENSION(nst)
EXTENSION(okt)      // OpenMPT & UADE: Oktalyzer
EXTENSION(plm)
EXTENSION(psm)
EXTENSION(pt36)
EXTENSION(ptm)
EXTENSION(sfx)      // OpenMPT & UADE: Sound-FX
EXTENSION(sfx2)
EXTENSION(st26)
EXTENSION(stk)
EXTENSION(stm)
EXTENSION(stp)
EXTENSION(ult)
EXTENSION(wow)
EXTENSION(gdm)
EXTENSION(mo3)
EXTENSION(oxm)
EXTENSION(umx)
EXTENSION(xpk)
EXTENSION(ppm)
EXTENSION(mmcmp)
EXTENSION(hvl)
EXTENSION(ahx)
EXTENSION(bp)       // SoundMon & UAE: SoundMon2.0
EXTENSION(ym)
EXTENSION(dsym)
EXTENSION(fmt)
EXTENSION(mus)      // OpenMPT: ? & Sidplay: ? & UADE: UFO
EXTENSION(stx)
EXTENSION(symmod)
EXTENSION(smod)
EXTENSION(fc)
EXTENSION(rsid)
EXTENSION(psid)
EXTENSION(v2m)
EXTENSION(sndh)
EXTENSION(sc68)
EXTENSION(hsc)
EXTENSION(sng)      // Adlib: ? : UADE: ZoundMonitor
EXTENSION(wlf)
EXTENSION(adlib)
EXTENSION(a2m)
EXTENSION(amd)
EXTENSION(bam)
EXTENSION(cmf)
EXTENSION(d00)
EXTENSION(dfm)
EXTENSION(hsp)
EXTENSION(ksm)
EXTENSION(mad)
EXTENSION(ims)      // Adlib: Midi/IMS & UADE: ImagesMusicSystem
EXTENSION(mdi)
EXTENSION(mid)
EXTENSION(sci)
EXTENSION(laa)
EXTENSION(mkj)
EXTENSION(cff)
EXTENSION(dmo)
EXTENSION(mtk)
EXTENSION(rad)
EXTENSION(rac)
EXTENSION(raw)
EXTENSION(sat)
EXTENSION(sa2)
EXTENSION(xad)
EXTENSION(bmf)
EXTENSION(lds)
EXTENSION(m)
EXTENSION(rol)
EXTENSION(xsm)
EXTENSION(dro)
EXTENSION(msc)
EXTENSION(rix)
EXTENSION(adl)
EXTENSION(jbm)
EXTENSION(got)
EXTENSION(vgm)
EXTENSION(vgz)
EXTENSION(sop)
EXTENSION(hsq)
EXTENSION(sqx)
EXTENSION(sdb)
EXTENSION(agd)
EXTENSION(ha2)
EXTENSION(bp3)      // SoundMon & UAE: SoundMon2.2
EXTENSION(sap)
EXTENSION(cmc)
EXTENSION(cm3)
EXTENSION(cmr)
EXTENSION(cms)
EXTENSION(dmc)
EXTENSION(dlt)
EXTENSION(mpt)
EXTENSION(mpd)
EXTENSION(rmt)
EXTENSION(tmc)
EXTENSION(tm8)
EXTENSION(tm2)
EXTENSION(tfm)
EXTENSION(mp3)
EXTENSION(flac)
EXTENSION(ogg)
EXTENSION(ay)       // Ayfly & GME & NEZplug
EXTENSION(vtx)
EXTENSION(psg)
EXTENSION(asc)
EXTENSION(pt1)
EXTENSION(pt2)
EXTENSION(pt3)
EXTENSION(stc)
EXTENSION(sqt)      // AyFly: ? & UADE: Quartet_PSG
EXTENSION(psc)
EXTENSION(gbs)      // GBSPlay & GME & NEZplug
EXTENSION(gbr)      // GBSPlay & NEZplug
EXTENSION(gb)
EXTENSION(gym)
EXTENSION(hes)      // GME & NEZplug
EXTENSION(kss)      // KSS & GME & NEZplug
EXTENSION(nsf)      // GME & NEZplug
EXTENSION(nsfe)     // GME & NEZplug
EXTENSION(spc)
EXTENSION(rsn)
EXTENSION(mdx)
EXTENSION(mdxPk)
EXTENSION(s98)
EXTENSION(aps)      // UADE: AProSys
EXTENSION(ast)      // UADE: ActionAmics
EXTENSION(adpcm)    // UADE: ADPCM_mono
EXTENSION(amc)      // UADE: AM-Composer
EXTENSION(abk)      // UADE: AMOS
EXTENSION(hot)      // UADE: Anders_0land
EXTENSION(aam)      // UADE: ArtAndMagic
EXTENSION(alp)      // UADE: Alcatraz_Packer
EXTENSION(bye)      // UADE: Andrew_Parton
EXTENSION(aon)      // UADE: ArtOfNoise
EXTENSION(ash)      // UADE: Ashley_Hogg
EXTENSION(adsc)     // UADE: AudioSculpture
EXTENSION(bss)      // UADE: BeathovenSynthesizer
EXTENSION(bd)       // UADE: BenDaglish
EXTENSION(bds)      // UADE: BenDaglish-SID
EXTENSION(uds)      // UADE: BladePacker
EXTENSION(kris)     // UADE: ChipTracker
EXTENSION(cin)      // UADE: Cinemaware
EXTENSION(core)     // UADE: CoreDesign
EXTENSION(cus)      // UADE: custom
EXTENSION(cm)       // UADE: CustomMade
EXTENSION(dz)       // UADE: DariusZendeh
EXTENSION(dl)       // UADE: DaveLowe
EXTENSION(dl_deli)  // UADE: DaveLowe_Deli
EXTENSION(dln)      // UADE: DaveLoweNew
EXTENSION(dh)       // UADE: DavidHanney
EXTENSION(dw)       // UADE: DavidWhittaker
EXTENSION(dm)       // UADE: DeltaMusic1.3
EXTENSION(dm2)      // UADE: DeltaMusic2.0
EXTENSION(dsr)      // UADE: Desire
EXTENSION(dsc)      // UADE: DigitalSonixChrome
EXTENSION(dss)      // UADE: DigitalSoundStudio
EXTENSION(dns)      // UADE: DynamicSynthesizer
EXTENSION(ems)      // UADE: EMS & EMS-6
EXTENSION(ex)       // UADE: FashionTracker
EXTENSION(fred)     // UADE: Fred
EXTENSION(gray)     // UADE: FredGray
EXTENSION(bsi)      // UADE: FutureComposer-BSI
EXTENSION(fp)       // UADE: FuturePlayer
EXTENSION(fw)       // UADE: ForgottenWorlds_Game
EXTENSION(glue)     // UADE: GlueMon
EXTENSION(gmc)      // UADE: GMC
EXTENSION(ea)       // UADE: EarAche
EXTENSION(hd)       // UADE: HowieDavies
EXTENSION(hipc)     // UADE: JochenHippel-CoSo
EXTENSION(emod)     // UADE: QuadraComposer
EXTENSION(dum)      // UADE: Infogrames
EXTENSION(is)       // UADE: InStereo
EXTENSION(is20)     // UADE: InStereo2.0
EXTENSION(jam)      // UADE: JamCracker
EXTENSION(jmf)      // UADE: JankoMrsicFlogel
EXTENSION(js)       // UADE: Janne_Salmijarvi_Optimizer
EXTENSION(jb)       // UADE: JasonBrooke
EXTENSION(jpn)      // UADE: JasonPage
EXTENSION(jpo)      // UADE: JasonPage_JP & UADE: SteveTurner
EXTENSION(jt)       // UADE: JeroenTel
EXTENSION(jo)       // UADE: JesperOlsen
EXTENSION(hip)      // UADE: JochenHippel
EXTENSION(hip7)     // UADE: JochenHippel-7V
EXTENSION(hst)      // UADE: Jochen_Hippel_ST
EXTENSION(kim)      // UADE: Kim_Christensen
EXTENSION(kh)       // UADE: KrisHatlelid
EXTENSION(pt)       // UADE: Laxity
EXTENSION(lme)      // UADE: LegglessMusicEditor
EXTENSION(mon)      // UADE: ManiacsOfNoise
EXTENSION(mfp)      // UADE: MagneticFieldsPacker
EXTENSION(hn)       // UADE: MajorTom
EXTENSION(mc)       // UADE: Mark_Cooksey
EXTENSION(mco)      // UADE: Mark_Cooksey_Old
EXTENSION(mk2)      // UADE: MarkII
EXTENSION(avp)      // UADE: MartinWalker
EXTENSION(max)      // UADE: Maximum_Effect
EXTENSION(midi)     // UADE: MIDI-Loriciel
EXTENSION(md)       // UADE: MikeDavies
EXTENSION(mosh)     // UADE: Mosh_Packer
EXTENSION(mmdc)     // UADE: MMDC
EXTENSION(dmu)      // UADE: Mugician
EXTENSION(dmu2)     // UADE: MugicianII
EXTENSION(ma)       // UADE: MusicAssembler
EXTENSION(mm4)      // UADE: MusicMaker-4V
EXTENSION(mm8)      // UADE: MusicMaker-8V
EXTENSION(npp)      // UADE: Nick_Pelling_Packer
EXTENSION(ntp)      // UADE: NovoTradePacker
EXTENSION(two)      // UADE: NTSP-system
EXTENSION(one)      // UADE: onEscapee
EXTENSION(dat)      // UADE: PaulRobotham
EXTENSION(ps)       // UADE: PaulShields
EXTENSION(snk)      // UADE: PaulSummers
EXTENSION(pat)      // UADE: Paul_Tonge
EXTENSION(pvp)      // UADE: PeterVerswyvelen
EXTENSION(pap)      // UADE: PierreAdane
EXTENSION(pn)       // UADE: Pokeynoise
EXTENSION(psa)      // UADE: ProfessionalSoundArtists
EXTENSION(puma)     // UADE: PumaTracker
EXTENSION(rj)       // UADE: RichardJoseph
EXTENSION(rjp)      // UADE: RichardJoseph_Player
EXTENSION(riff)     // UADE: RiffRaff
EXTENSION(rh)       // UADE: RobHubbard
EXTENSION(rho)      // UADE: RobHubbard_ST
EXTENSION(scumm)    // UADE: SCUMM
EXTENSION(scn)      // UADE: SeanConnolly
EXTENSION(scr)      // UADE: SeanConran
EXTENSION(sid1)     // UADE: SIDMon1.0
EXTENSION(sid2)     // UADE: SIDMon2.0
EXTENSION(mok)      // UADE: Silmarils
EXTENSION(sa)       // UADE: SonicArranger
EXTENSION(smus)     // UADE: SonixMusicDriver
EXTENSION(spl)      // UADE: SoundProgrammingLanguage
EXTENSION(sc)       // UADE: SoundControl
EXTENSION(psf)      // UADE: SoundFactory
EXTENSION(tw)       // UADE: SoundImages
EXTENSION(sm)       // UADE: SoundMaster
EXTENSION(sm2)      // UADE: SoundMaster
EXTENSION(sm3)      // UADE: SoundMaster
EXTENSION(smpro)    // UADE: SoundMaster
EXTENSION(sjs)      // UADE: SoundPlayer
EXTENSION(jd)       // UADE: Special-FX
EXTENSION(doda)     // UADE: Special-FX_ST
EXTENSION(sas)      // UADE: SpeedyA1System
EXTENSION(ss)       // UADE: SpeedySystem
EXTENSION(sb)       // UADE: SteveBarrett
EXTENSION(sun)      // UADE: SUN-Tronic
EXTENSION(syn)      // UADE: Synth
EXTENSION(sdr)      // UADE: SynthDream
EXTENSION(osp)      // UADE: SynthPack
EXTENSION(synmod)   // UADE: SynTracker
EXTENSION(tcb)      // UADE: TCB_Tracker
EXTENSION(mdst)     // UADE: TFMX_ST
EXTENSION(thm)      // UADE: ThomasHermann
EXTENSION(tmk)      // UADE: TimeTracker
EXTENSION(tits)     // UADE: Titanics_Packer
EXTENSION(tme)      // UADE: TheMusicalEnlightenment
EXTENSION(sg)       // UADE: TomyTracker
EXTENSION(dp)       // UADE: Tronic
EXTENSION(vss)      // UADE: VoodooSupremeSynthesizer
EXTENSION(wb)       // UADE: WallyBeben
EXTENSION(ml)       // UADE: MusiclineEditor
EXTENSION(agi)      // UADE: Sierra-AGI
EXTENSION(tpu)      // UADE: DirkBialluch
EXTENSION(qpa)      // UADE: Quartet
EXTENSION(qts)      // UADE: Quartet_ST
EXTENSION(miniqsf)  // Highly Quixotic
EXTENSION(qsfPk)    // Highly Quixotic
EXTENSION(minigsf)  // Highly Advanced
EXTENSION(gsfPk)    // Highly Advanced
EXTENSION(ymst)     // UADE: YMST
EXTENSION(wav)      // WAV
EXTENSION(sid)      // SidPlay & UADE: SidMon1
EXTENSION(mug)      // UADE: MugicianII
EXTENSION(mso)      // UADE: Medley
EXTENSION(ptk)      // ProTrekkr
EXTENSION(mdy)      // Adlib: AdLib MIDI/IMS Format
EXTENSION(mcr)      // UADE: Mark_Cooksey_Old
EXTENSION(mgb)      // Gameboy Tracker: no known replay :(
EXTENSION(ixs)      // iXalance
EXTENSION(mgs)      // KSS
EXTENSION(bgm)      // KSS
EXTENSION(opx)      // KSS
EXTENSION(mpk)      // KSS
EXTENSION(mbm)      // KSS
EXTENSION(sgc)      // NEZplug
EXTENSION(nsd)      // NEZplug