#undef BASE_OF_ZERO
#undef BUILD_2A03
#undef BUILD_HUC6280
#undef BUILD_M6502
#undef BUILD_M65C02
#undef B_FLAG
#undef C_FLAG
#undef DEF_ADC
#undef DEF_AND
#undef DEF_ASL
#undef DEF_BBR
#undef DEF_BBS
#undef DEF_BIT
#undef DEF_BRA
#undef DEF_CMP
#undef DEF_CPX
#undef DEF_CPY
#undef DEF_DEC
#undef DEF_EOR
#undef DEF_INC
#undef DEF_JMP
#undef DEF_JMPBUG
#undef DEF_LDA
#undef DEF_LDX
#undef DEF_LDY
#undef DEF_LSR
#undef DEF_ORA
#undef DEF_RMB
#undef DEF_ROL
#undef DEF_ROR
#undef DEF_SBC
#undef DEF_SMB
#undef DEF_STA
#undef DEF_STX
#undef DEF_STY
#undef DEF_STZ
#undef DEF_TRB
#undef DEF_TSB
#undef DEF_TST
#undef D_FLAG
#undef D_Opco61
#undef D_Opco65
#undef D_Opco69
#undef D_Opco6D
#undef D_Opco71
#undef D_Opco72
#undef D_Opco75
#undef D_Opco79
#undef D_Opco7D
#undef D_OpcoE1
#undef D_OpcoE5
#undef D_OpcoE9
#undef D_OpcoED
#undef D_OpcoF1
#undef D_OpcoF2
#undef D_OpcoF5
#undef D_OpcoF9
#undef D_OpcoFD
#undef IRQ_BRK
#undef IRQ_INIT
#undef IRQ_INT
#undef IRQ_INT1
#undef IRQ_NMI
#undef IRQ_RESET
#undef IRQ_TIMER
#undef I_FLAG
#undef KAI_ABS
#undef KAI_ABSX
#undef KAI_ABSY
#undef KAI_IMM
#undef KAI_IMM16
#undef KAI_INDY
#undef KAI_ZP
#undef KAI_ZPX
#undef KA_ABS
#undef KA_ABSX
#undef KA_ABSX_
#undef KA_ABSY
#undef KA_ABSY_
#undef KA_IMM
#undef KA_IMM16
#undef KA_IND
#undef KA_INDX
#undef KA_INDY
#undef KA_INDY_
#undef KA_ZP
#undef KA_ZPX
#undef KA_ZPY
#undef KI_ADDCLOCK
#undef KI_READWORD
#undef KI_READWORDBUG
#undef KI_READWORDZP
#undef KMI_ADC
#undef KMI_ADC_D
#undef KMI_POSTT
#undef KMI_PRET
#undef KMI_SBC
#undef KMI_SBC_D
#undef KM_ALUADDER
#undef KM_ALUADDER_D
#undef KM_AND
#undef KM_ASL
#undef KM_BIT
#undef KM_BRA
#undef KM_CMP
#undef KM_CPX
#undef KM_CPY
#undef KM_DEC
#undef KM_EOR
#undef KM_INC
#undef KM_LD
#undef KM_LSR
#undef KM_ORA
#undef KM_POP
#undef KM_PUSH
#undef KM_ROL
#undef KM_ROR
#undef KM_TRB
#undef KM_TSB
#undef KM_TST
#undef K_EXE
#undef K_EXEC
#undef K_OPEXEC
#undef K_READ
#undef K_READMPR
#undef K_READNP
#undef K_READZP
#undef K_WRITE
#undef K_WRITE6270
#undef K_WRITEMPR
#undef K_WRITENP
#undef K_WRITEZP
#undef N_FLAG
#undef OP__
#undef OP_d
#undef OPt_
#undef OPtd
#undef OPxx
#undef Opcode00
#undef Opcode01
#undef Opcode02
#undef Opcode03
#undef Opcode04
#undef Opcode05
#undef Opcode06
#undef Opcode07
#undef Opcode08
#undef Opcode09
#undef Opcode0A
#undef Opcode0C
#undef Opcode0D
#undef Opcode0E
#undef Opcode0F
#undef Opcode10
#undef Opcode11
#undef Opcode12
#undef Opcode13
#undef Opcode14
#undef Opcode15
#undef Opcode16
#undef Opcode17
#undef Opcode18
#undef Opcode19
#undef Opcode1A
#undef Opcode1C
#undef Opcode1D
#undef Opcode1E
#undef Opcode1F
#undef Opcode20
#undef Opcode21
#undef Opcode22
#undef Opcode23
#undef Opcode24
#undef Opcode25
#undef Opcode26
#undef Opcode27
#undef Opcode28
#undef Opcode29
#undef Opcode2A
#undef Opcode2C
#undef Opcode2D
#undef Opcode2E
#undef Opcode2F
#undef Opcode30
#undef Opcode31
#undef Opcode32
#undef Opcode34
#undef Opcode35
#undef Opcode36
#undef Opcode37
#undef Opcode38
#undef Opcode39
#undef Opcode3A
#undef Opcode3C
#undef Opcode3D
#undef Opcode3E
#undef Opcode3F
#undef Opcode40
#undef Opcode41
#undef Opcode42
#undef Opcode43
#undef Opcode44
#undef Opcode45
#undef Opcode46
#undef Opcode47
#undef Opcode48
#undef Opcode49
#undef Opcode4A
#undef Opcode4C
#undef Opcode4D
#undef Opcode4E
#undef Opcode4F
#undef Opcode50
#undef Opcode51
#undef Opcode52
#undef Opcode53
#undef Opcode54
#undef Opcode55
#undef Opcode56
#undef Opcode57
#undef Opcode58
#undef Opcode59
#undef Opcode5A
#undef Opcode5D
#undef Opcode5E
#undef Opcode5F
#undef Opcode60
#undef Opcode61
#undef Opcode62
#undef Opcode64
#undef Opcode65
#undef Opcode66
#undef Opcode67
#undef Opcode68
#undef Opcode69
#undef Opcode6A
#undef Opcode6C
#undef Opcode6D
#undef Opcode6E
#undef Opcode6F
#undef Opcode70
#undef Opcode71
#undef Opcode72
#undef Opcode73
#undef Opcode74
#undef Opcode75
#undef Opcode76
#undef Opcode77
#undef Opcode78
#undef Opcode79
#undef Opcode7A
#undef Opcode7C
#undef Opcode7D
#undef Opcode7E
#undef Opcode7F
#undef Opcode80
#undef Opcode81
#undef Opcode82
#undef Opcode83
#undef Opcode84
#undef Opcode85
#undef Opcode86
#undef Opcode87
#undef Opcode88
#undef Opcode89
#undef Opcode8A
#undef Opcode8C
#undef Opcode8D
#undef Opcode8E
#undef Opcode8F
#undef Opcode90
#undef Opcode91
#undef Opcode92
#undef Opcode93
#undef Opcode94
#undef Opcode95
#undef Opcode96
#undef Opcode97
#undef Opcode98
#undef Opcode99
#undef Opcode9A
#undef Opcode9C
#undef Opcode9D
#undef Opcode9E
#undef Opcode9F
#undef OpcodeA0
#undef OpcodeA1
#undef OpcodeA2
#undef OpcodeA3
#undef OpcodeA4
#undef OpcodeA5
#undef OpcodeA6
#undef OpcodeA7
#undef OpcodeA8
#undef OpcodeA9
#undef OpcodeAA
#undef OpcodeAC
#undef OpcodeAD
#undef OpcodeAE
#undef OpcodeAF
#undef OpcodeB0
#undef OpcodeB1
#undef OpcodeB2
#undef OpcodeB3
#undef OpcodeB4
#undef OpcodeB5
#undef OpcodeB6
#undef OpcodeB7
#undef OpcodeB8
#undef OpcodeB9
#undef OpcodeBA
#undef OpcodeBC
#undef OpcodeBD
#undef OpcodeBE
#undef OpcodeBF
#undef OpcodeC0
#undef OpcodeC1
#undef OpcodeC2
#undef OpcodeC3
#undef OpcodeC4
#undef OpcodeC5
#undef OpcodeC6
#undef OpcodeC7
#undef OpcodeC8
#undef OpcodeC9
#undef OpcodeCA
#undef OpcodeCC
#undef OpcodeCD
#undef OpcodeCE
#undef OpcodeCF
#undef OpcodeD0
#undef OpcodeD1
#undef OpcodeD2
#undef OpcodeD3
#undef OpcodeD4
#undef OpcodeD5
#undef OpcodeD6
#undef OpcodeD7
#undef OpcodeD8
#undef OpcodeD9
#undef OpcodeDA
#undef OpcodeDD
#undef OpcodeDE
#undef OpcodeDF
#undef OpcodeE0
#undef OpcodeE1
#undef OpcodeE3
#undef OpcodeE4
#undef OpcodeE5
#undef OpcodeE6
#undef OpcodeE7
#undef OpcodeE8
#undef OpcodeE9
#undef OpcodeEA
#undef OpcodeEC
#undef OpcodeED
#undef OpcodeEE
#undef OpcodeEF
#undef OpcodeF0
#undef OpcodeF1
#undef OpcodeF2
#undef OpcodeF3
#undef OpcodeF4
#undef OpcodeF5
#undef OpcodeF6
#undef OpcodeF7
#undef OpcodeF8
#undef OpcodeF9
#undef OpcodeFA
#undef OpcodeFD
#undef OpcodeFE
#undef OpcodeFF
#undef R_FLAG
#undef TD_Opc61
#undef TD_Opc65
#undef TD_Opc69
#undef TD_Opc6D
#undef TD_Opc71
#undef TD_Opc72
#undef TD_Opc75
#undef TD_Opc79
#undef TD_Opc7D
#undef T_FLAG
#undef T_Opco01
#undef T_Opco05
#undef T_Opco09
#undef T_Opco0D
#undef T_Opco11
#undef T_Opco12
#undef T_Opco15
#undef T_Opco19
#undef T_Opco1D
#undef T_Opco21
#undef T_Opco25
#undef T_Opco29
#undef T_Opco2D
#undef T_Opco31
#undef T_Opco32
#undef T_Opco35
#undef T_Opco39
#undef T_Opco3D
#undef T_Opco41
#undef T_Opco45
#undef T_Opco49
#undef T_Opco4D
#undef T_Opco51
#undef T_Opco52
#undef T_Opco55
#undef T_Opco59
#undef T_Opco5D
#undef T_Opco61
#undef T_Opco65
#undef T_Opco69
#undef T_Opco6D
#undef T_Opco71
#undef T_Opco72
#undef T_Opco75
#undef T_Opco79
#undef T_Opco7D
#undef VEC_BRK
#undef VEC_INT
#undef VEC_INT1
#undef VEC_NMI
#undef VEC_RESET
#undef VEC_TIMER
#undef V_FLAG
#undef Z_FLAG
#undef __CONTEXT
#undef __CONTEXT_
#undef __THISP
#undef __THISP_
#undef __THIS_USER_
#undef __THIS__
#undef cl_table
