#pragma once

#define REPLAYER_VERSION_MAJOR 0
#define REPLAYER_VERSION_MINOR 16
#define REPLAYER_VERSION_PATCH 12

#define VER_STRINGIZE(x) #x
#define VER_STR(x) VER_STRINGIZE(x)

#define REPLAYER_VERSION_STRING VER_STR(REPLAYER_VERSION_MAJOR) ", " VER_STR(REPLAYER_VERSION_MINOR) ", " VER_STR(REPLAYER_VERSION_PATCH)

#define REPLAYER_COPYRIGHT "Copyright (c) 2023-2025 Arnaud Nény"

#ifdef _WIN64
#define REPLAYER_OS_STUB ""
#else
#define REPLAYER_OS_STUB "-win32"
#endif
