#define FAAD2_VERSION "2.11.1"

#define APPLY_DRC 1
#define HAVE_INTTYPES_H 1
#define HAVE_MEMCPY 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define STDC_HEADERS 1
#define HAVE_LRINTF 1
#define PACKAGE_VERSION FAAD2_VERSION
